// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlc

import (
	"context"
	"database/sql"
)

const accountAncestors = `-- name: AccountAncestors :many
WITH RECURSIVE anc(id, parent_id) AS (
  SELECT a.id, a.parent_id FROM accounts a WHERE a.id = ?
  UNION ALL
  SELECT a.id, a.parent_id FROM accounts a
  JOIN anc ON a.id = anc.parent_id
)
SELECT anc.id FROM anc
`

// Self + transitive ancestor chain of an account (walk parent_id upward).
// Propagation adds an assigned subsidiary to every strict ancestor; the store
// skips self.
func (q *Queries) AccountAncestors(ctx context.Context, id int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, accountAncestors, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountDescendants = `-- name: AccountDescendants :many
WITH RECURSIVE des(id) AS (
  SELECT a.id FROM accounts a WHERE a.id = ?
  UNION ALL
  SELECT a.id FROM accounts a
  JOIN des ON a.parent_id = des.id
)
SELECT des.id FROM des
`

// Self + transitive closure of an account (walk children downward). The store's
// move cycle check (new parent must not be self nor any descendant) relies on
// self being included.
func (q *Queries) AccountDescendants(ctx context.Context, id int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, accountDescendants, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountSubsidiaries = `-- name: AccountSubsidiaries :many
SELECT subsidiary_id FROM account_subsidiaries
WHERE account_id = ?
ORDER BY subsidiary_id
`

// The subsidiary id set an account currently maps (order-insensitive; the store
// builds a set).
func (q *Queries) AccountSubsidiaries(ctx context.Context, accountID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, accountSubsidiaries, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var subsidiary_id int64
		if err := rows.Scan(&subsidiary_id); err != nil {
			return nil, err
		}
		items = append(items, subsidiary_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountTree = `-- name: AccountTree :many
WITH RECURSIVE tree(id, parent_id, type, active, reconcilable, open_item, sort_order, path) AS (
  SELECT a.id, a.parent_id, a.type, a.active, a.reconcilable, a.open_item, a.sort_order,
         printf('%020d.%020d', a.sort_order, a.id)
  FROM accounts a
  WHERE a.parent_id IS NULL
  UNION ALL
  SELECT a.id, a.parent_id, a.type, a.active, a.reconcilable, a.open_item, a.sort_order,
         t.path || '/' || printf('%020d.%020d', a.sort_order, a.id)
  FROM accounts a
  JOIN tree t ON a.parent_id = t.id
)
SELECT tree.id, tree.parent_id, tree.type, tree.active, tree.reconcilable, tree.open_item, tree.sort_order,
       CAST(COALESCE(
         (SELECT an1.name FROM account_names an1 WHERE an1.account_id = tree.id AND an1.lang = ?),
         (SELECT an2.name FROM account_names an2 WHERE an2.account_id = tree.id AND an2.lang = 'en'),
         (SELECT anx.name FROM account_names anx WHERE anx.account_id = tree.id ORDER BY anx.lang LIMIT 1),
         ''
       ) AS TEXT) AS name
FROM tree
ORDER BY tree.path
`

type AccountTreeRow struct {
	ID           int64
	ParentID     sql.NullInt64
	Type         string
	Active       int64
	Reconcilable int64
	OpenItem     int64
	SortOrder    int64
	Name         string
}

// All accounts in DEPTH-FIRST (pre-order) order, resolving each account's name via
// the fallback chain requested-lang -> en -> any (p05.3). Multiple roots are
// allowed (accounts have no single-root constraint); each root subtree is emitted
// in order. Path = zero-padded (sort_order, id) per level, so ORDER BY path is a
// true pre-order traversal.
//
// Name resolution is a COALESCE over correlated subqueries against account_names:
// (1) the requested lang, (2) 'en' (D14), (3) any name, chosen deterministically
// by ORDER BY lang LIMIT 1 so results are stable. The trailing ” keeps the column
// non-null (an account with no names at all resolves to empty, and sqlc types the
// column as a plain string), so the store's TreeRow mapping is unchanged.
func (q *Queries) AccountTree(ctx context.Context, lang string) ([]AccountTreeRow, error) {
	rows, err := q.db.QueryContext(ctx, accountTree, lang)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountTreeRow
	for rows.Next() {
		var i AccountTreeRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Type,
			&i.Active,
			&i.Reconcilable,
			&i.OpenItem,
			&i.SortOrder,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountTreeBySubsidiary = `-- name: AccountTreeBySubsidiary :many
WITH RECURSIVE tree(id, parent_id, type, active, reconcilable, open_item, sort_order, path) AS (
  SELECT a.id, a.parent_id, a.type, a.active, a.reconcilable, a.open_item, a.sort_order,
         printf('%020d.%020d', a.sort_order, a.id)
  FROM accounts a
  WHERE a.parent_id IS NULL
  UNION ALL
  SELECT a.id, a.parent_id, a.type, a.active, a.reconcilable, a.open_item, a.sort_order,
         t.path || '/' || printf('%020d.%020d', a.sort_order, a.id)
  FROM accounts a
  JOIN tree t ON a.parent_id = t.id
)
SELECT tree.id, tree.parent_id, tree.type, tree.active, tree.reconcilable, tree.open_item, tree.sort_order,
       CAST(COALESCE(
         (SELECT an1.name FROM account_names an1 WHERE an1.account_id = tree.id AND an1.lang = ?),
         (SELECT an2.name FROM account_names an2 WHERE an2.account_id = tree.id AND an2.lang = 'en'),
         (SELECT anx.name FROM account_names anx WHERE anx.account_id = tree.id ORDER BY anx.lang LIMIT 1),
         ''
       ) AS TEXT) AS name
FROM tree
JOIN account_subsidiaries asub ON asub.account_id = tree.id AND asub.subsidiary_id = ?
ORDER BY tree.path
`

type AccountTreeBySubsidiaryParams struct {
	Lang         string
	SubsidiaryID int64
}

type AccountTreeBySubsidiaryRow struct {
	ID           int64
	ParentID     sql.NullInt64
	Type         string
	Active       int64
	Reconcilable int64
	OpenItem     int64
	SortOrder    int64
	Name         string
}

// Like AccountTree but restricted to accounts mapped to a specific subsidiary.
// The filter is applied at output (the recursion still walks the whole tree so
// paths stay well-defined); a mapped child under an unmapped parent is dropped,
// matching "accounts mapped to subFilter". sqlc-sqlite's nullable-? handling is
// awkward, so this is a separate query (mirrors SubTree/Descendants split).
//
// Name resolution is the SAME requested-lang -> en -> any COALESCE chain as
// AccountTree (p05.3); see that query's comment for the rationale of each branch
// and the trailing ” (keeps the column non-null / a plain string in sqlc).
func (q *Queries) AccountTreeBySubsidiary(ctx context.Context, arg AccountTreeBySubsidiaryParams) ([]AccountTreeBySubsidiaryRow, error) {
	rows, err := q.db.QueryContext(ctx, accountTreeBySubsidiary, arg.Lang, arg.SubsidiaryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountTreeBySubsidiaryRow
	for rows.Next() {
		var i AccountTreeBySubsidiaryRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Type,
			&i.Active,
			&i.Reconcilable,
			&i.OpenItem,
			&i.SortOrder,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const allAccountCodes = `-- name: AllAccountCodes :many
SELECT id, parent_id, form990_code
FROM accounts
ORDER BY id
`

type AllAccountCodesRow struct {
	ID          int64
	ParentID    sql.NullInt64
	Form990Code sql.NullString
}

// Flat (id, parent_id, own form990_code) for every account. Effective990Codes
// resolves the nearest-ancestor code (D25) in Go from this: sqlc's sqlite analyzer
// cannot resolve a recursive CTE column that is CARRIED (a self-referencing
// COALESCE or a passed-through id) in the OUTPUT projection -- it reports the
// carried column 'does not exist'. Rather than fight that limitation with an
// awkward closure query, the store walks parent_id in memory (the chart is small;
// one pass is O(n * depth)). Ordered by id for deterministic resolution.
func (q *Queries) AllAccountCodes(ctx context.Context) ([]AllAccountCodesRow, error) {
	rows, err := q.db.QueryContext(ctx, allAccountCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AllAccountCodesRow
	for rows.Next() {
		var i AllAccountCodesRow
		if err := rows.Scan(&i.ID, &i.ParentID, &i.Form990Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countChildAccountsWithSub = `-- name: CountChildAccountsWithSub :one
SELECT COUNT(*) FROM accounts child
JOIN account_subsidiaries asub ON asub.account_id = child.id
WHERE child.parent_id = ? AND asub.subsidiary_id = ?
`

type CountChildAccountsWithSubParams struct {
	ParentID     sql.NullInt64
	SubsidiaryID int64
}

// Number of DIRECT child accounts that still map a given subsidiary. Removing a
// subsidiary from an account is blocked while this is > 0 (ErrSubInUseByChild):
// the superset invariant (parent set superset-of union of children's) forbids a
// parent dropping a sub a child still holds. Direct children suffice because the
// invariant holds inductively.
func (q *Queries) CountChildAccountsWithSub(ctx context.Context, arg CountChildAccountsWithSubParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChildAccountsWithSub, arg.ParentID, arg.SubsidiaryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAccountSubsidiary = `-- name: DeleteAccountSubsidiary :exec
DELETE FROM account_subsidiaries
WHERE account_id = ? AND subsidiary_id = ?
`

type DeleteAccountSubsidiaryParams struct {
	AccountID    int64
	SubsidiaryID int64
}

// Remove one membership. For op=delete the version row is captured BEFORE this
// runs (the live row must still exist to snapshot from) -- see the store's
// removal-op ordering comment.
func (q *Queries) DeleteAccountSubsidiary(ctx context.Context, arg DeleteAccountSubsidiaryParams) error {
	_, err := q.db.ExecContext(ctx, deleteAccountSubsidiary, arg.AccountID, arg.SubsidiaryID)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, parent_id, type, default_currency, functional_class, form990_code,
       intercompany, reconcilable, active, sort_order, created_at, default_program_id,
       current_cash, open_item
FROM accounts
WHERE id = ?
`

// Column order matches the accounts table's PHYSICAL order (default_program_id was
// ADDed last by 00008; current_cash + open_item ADDed last by 00027), so sqlc maps
// the result to the sqlc.Account model rather than a bespoke GetAccountRow --
// accounts.go depends on GetAccount returning Account.
func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Type,
		&i.DefaultCurrency,
		&i.FunctionalClass,
		&i.Form990Code,
		&i.Intercompany,
		&i.Reconcilable,
		&i.Active,
		&i.SortOrder,
		&i.CreatedAt,
		&i.DefaultProgramID,
		&i.CurrentCash,
		&i.OpenItem,
	)
	return i, err
}

const getAccountName = `-- name: GetAccountName :one
SELECT account_id, lang, name
FROM account_names
WHERE account_id = ? AND lang = ?
`

type GetAccountNameParams struct {
	AccountID int64
	Lang      string
}

func (q *Queries) GetAccountName(ctx context.Context, arg GetAccountNameParams) (AccountName, error) {
	row := q.db.QueryRowContext(ctx, getAccountName, arg.AccountID, arg.Lang)
	var i AccountName
	err := row.Scan(&i.AccountID, &i.Lang, &i.Name)
	return i, err
}

const getForm990Line = `-- name: GetForm990Line :one
SELECT code, part, line, label, account_types, sort
FROM form990_lines
WHERE code = ?
`

// A 990 line's allowed account types (CSV). The store splits account_types on
// comma and checks membership (some lines allow more than one type), rejecting a
// code whose CSV omits the account's type (Err990TypeMismatch).
func (q *Queries) GetForm990Line(ctx context.Context, code string) (Form990Line, error) {
	row := q.db.QueryRowContext(ctx, getForm990Line, code)
	var i Form990Line
	err := row.Scan(
		&i.Code,
		&i.Part,
		&i.Line,
		&i.Label,
		&i.AccountTypes,
		&i.Sort,
	)
	return i, err
}

const hasAccountSubsidiary = `-- name: HasAccountSubsidiary :one
SELECT COUNT(*) FROM account_subsidiaries
WHERE account_id = ? AND subsidiary_id = ?
`

type HasAccountSubsidiaryParams struct {
	AccountID    int64
	SubsidiaryID int64
}

// 1 if the account already maps the subsidiary. Propagation uses this to skip
// ancestors that already hold the sub (no duplicate PK, no spurious version row).
func (q *Queries) HasAccountSubsidiary(ctx context.Context, arg HasAccountSubsidiaryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasAccountSubsidiary, arg.AccountID, arg.SubsidiaryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAccount = `-- name: InsertAccount :one

INSERT INTO accounts
  (parent_id, type, default_currency, functional_class, form990_code,
   default_program_id, intercompany, reconcilable, active, sort_order, created_at,
   current_cash, open_item)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertAccountParams struct {
	ParentID         sql.NullInt64
	Type             string
	DefaultCurrency  string
	FunctionalClass  sql.NullString
	Form990Code      sql.NullString
	DefaultProgramID sql.NullInt64
	Intercompany     int64
	Reconcilable     int64
	Active           int64
	SortOrder        int64
	CreatedAt        string
	CurrentCash      int64
	OpenItem         int64
}

// p05.2: account operations. All SQL for the store's account methods lives here
// (rule 6). This copies the version-append convention established in
// subsidiaries.sql (p04.2): the entity op does the live write inside the funnel's
// fn, then appends a snapshot-from-live version row, so the version row is
// byte-identical to the live row (Z3 can never diverge) and valid_from ==
// changes.at BY CONSTRUCTION.
//
// Two composite-key versioned tables appear here (account_names,
// account_subsidiaries). Their version-append queries copy InsertSubsidiaryVersion's
// shape verbatim, changing ONLY the entity_id/WHERE expression, per 00005 comments.
//
// NOTE: keep every comment and identifier in this file PURE ASCII. sqlc v1.31.1
// miscounts byte offsets when a query file contains multi-byte UTF-8, corrupting
// the generated SQL for the WHOLE file (see docs/DECISIONS.md p04.2).
// Live insert of an account. Row-local invariants (parent typeclass,
// functional-class-expense-only) are validated in the store BEFORE this runs and
// backstopped by triggers. default_program_id is validated in the store as R/E-only
// (D24). Returns the new id for the store to snapshot + return.
func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertAccount,
		arg.ParentID,
		arg.Type,
		arg.DefaultCurrency,
		arg.FunctionalClass,
		arg.Form990Code,
		arg.DefaultProgramID,
		arg.Intercompany,
		arg.Reconcilable,
		arg.Active,
		arg.SortOrder,
		arg.CreatedAt,
		arg.CurrentCash,
		arg.OpenItem,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertAccountNameVersion = `-- name: InsertAccountNameVersion :exec
INSERT INTO account_names_versions
  (entity_id, change_id, valid_from, op, lang, name)
SELECT an.account_id, c.id, c.at, ?, an.lang, an.name
FROM account_names an, changes c
WHERE c.id = ? AND an.account_id = ? AND an.lang = ?
`

type InsertAccountNameVersionParams struct {
	Op        string
	ID        int64
	AccountID int64
	Lang      string
}

// Snapshot-from-live version append for a COMPOSITE (account_id, lang) name.
// entity_id = account_id; lang is both a snapshot column and part of the entity
// identity (00005). Must run AFTER the live upsert. Params (positional): op,
// change_id, account_id, lang -> generated fields Op, ID, AccountID, Lang.
func (q *Queries) InsertAccountNameVersion(ctx context.Context, arg InsertAccountNameVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertAccountNameVersion,
		arg.Op,
		arg.ID,
		arg.AccountID,
		arg.Lang,
	)
	return err
}

const insertAccountSubsidiary = `-- name: InsertAccountSubsidiary :exec
INSERT INTO account_subsidiaries (account_id, subsidiary_id)
VALUES (?, ?)
`

type InsertAccountSubsidiaryParams struct {
	AccountID    int64
	SubsidiaryID int64
}

// Add one (account_id, subsidiary_id) membership. Callers guard with
// HasAccountSubsidiary first (membership is a set; the PK forbids duplicates).
func (q *Queries) InsertAccountSubsidiary(ctx context.Context, arg InsertAccountSubsidiaryParams) error {
	_, err := q.db.ExecContext(ctx, insertAccountSubsidiary, arg.AccountID, arg.SubsidiaryID)
	return err
}

const insertAccountSubsidiaryVersion = `-- name: InsertAccountSubsidiaryVersion :exec
INSERT INTO account_subsidiaries_versions
  (entity_id, change_id, valid_from, op, subsidiary_id)
SELECT asub.account_id, c.id, c.at, ?, asub.subsidiary_id
FROM account_subsidiaries asub, changes c
WHERE c.id = ? AND asub.account_id = ? AND asub.subsidiary_id = ?
`

type InsertAccountSubsidiaryVersionParams struct {
	Op           string
	ID           int64
	AccountID    int64
	SubsidiaryID int64
}

// Snapshot-from-live version append for a COMPOSITE (account_id, subsidiary_id)
// membership. entity_id = account_id; subsidiary_id is both a snapshot column and
// part of the entity identity (00005). For op='create' this runs AFTER the live
// insert; for op='delete' it runs BEFORE the live delete (the row must still
// exist to snapshot). Params (positional): op, change_id, account_id,
// subsidiary_id -> generated fields Op, ID, AccountID, SubsidiaryID.
func (q *Queries) InsertAccountSubsidiaryVersion(ctx context.Context, arg InsertAccountSubsidiaryVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertAccountSubsidiaryVersion,
		arg.Op,
		arg.ID,
		arg.AccountID,
		arg.SubsidiaryID,
	)
	return err
}

const insertAccountVersion = `-- name: InsertAccountVersion :exec
INSERT INTO accounts_versions
  (entity_id, change_id, valid_from, op, parent_id, type, default_currency,
   functional_class, form990_code, default_program_id, intercompany, reconcilable,
   active, sort_order, created_at, current_cash, open_item)
SELECT a.id, c.id, c.at, ?, a.parent_id, a.type, a.default_currency,
       a.functional_class, a.form990_code, a.default_program_id, a.intercompany,
       a.reconcilable, a.active, a.sort_order, a.created_at, a.current_cash, a.open_item
FROM accounts a, changes c
WHERE c.id = ? AND a.id = ?
`

type InsertAccountVersionParams struct {
	Op   string
	ID   int64
	ID_2 int64
}

// Snapshot-from-live version append for accounts (STANDARD single-column entity,
// entity_id = accounts.id). Must run AFTER the live write. Snapshot column set
// matches 00005_accounts.sql + the 00008 default_program_id ripple exactly:
// adding default_program_id to accounts requires it here too, or Z3 (current ==
// latest snapshot) diverges for accounts touched after p07.1. Params (plain
// positional, each used once): op, change_id, entity_id -> generated fields Op,
// ID (change_id), ID_2 (entity_id).
func (q *Queries) InsertAccountVersion(ctx context.Context, arg InsertAccountVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertAccountVersion, arg.Op, arg.ID, arg.ID_2)
	return err
}

const intercompanyAccountIDs = `-- name: IntercompanyAccountIDs :many
SELECT id
FROM accounts
WHERE intercompany = 1
ORDER BY id
`

// Ids of every account flagged intercompany (D19). The report toolkit's
// IntercompanyNet sums these accounts' balances per currency across a consolidated
// scope to assert they net to zero (a nonzero residual becomes a warning row).
// Ordered by id for deterministic iteration.
func (q *Queries) IntercompanyAccountIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, intercompanyAccountIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForm990Lines = `-- name: ListForm990Lines :many
SELECT code, part, line, label, account_types, sort
FROM form990_lines
ORDER BY sort, code
`

// Every 990 line in report order (part, then line by sort). The chart-of-accounts
// form (p11.1) offers, for an account of a given type, only the lines whose
// account_types CSV includes that type; the CSV-membership filter runs in Go
// (Form990LinesForType) reusing the same predicate as check990Type, so this query
// stays a simple ordered fetch of the small static reference set (D25).
func (q *Queries) ListForm990Lines(ctx context.Context) ([]Form990Line, error) {
	rows, err := q.db.QueryContext(ctx, listForm990Lines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Form990Line
	for rows.Next() {
		var i Form990Line
		if err := rows.Scan(
			&i.Code,
			&i.Part,
			&i.Line,
			&i.Label,
			&i.AccountTypes,
			&i.Sort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE accounts
SET parent_id = ?, type = ?, default_currency = ?, functional_class = ?,
    form990_code = ?, default_program_id = ?, intercompany = ?, reconcilable = ?,
    active = ?, sort_order = ?, created_at = ?, current_cash = ?, open_item = ?
WHERE id = ?
`

type UpdateAccountParams struct {
	ParentID         sql.NullInt64
	Type             string
	DefaultCurrency  string
	FunctionalClass  sql.NullString
	Form990Code      sql.NullString
	DefaultProgramID sql.NullInt64
	Intercompany     int64
	Reconcilable     int64
	Active           int64
	SortOrder        int64
	CreatedAt        string
	CurrentCash      int64
	OpenItem         int64
	ID               int64
}

// Live update: move (parent) / flags / default currency / functional default /
// form990 code / default program / active / sort. The store reads the current row
// (GetAccount), overrides the caller's fields, and writes the full desired state
// here, keeping snapshot-from-live trivial. created_at is preserved
// (read-modify-write), and so is default_program_id unless changed -- the store
// carries cur.DefaultProgramID through, so an unrelated update never NULLs it.
func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.ExecContext(ctx, updateAccount,
		arg.ParentID,
		arg.Type,
		arg.DefaultCurrency,
		arg.FunctionalClass,
		arg.Form990Code,
		arg.DefaultProgramID,
		arg.Intercompany,
		arg.Reconcilable,
		arg.Active,
		arg.SortOrder,
		arg.CreatedAt,
		arg.CurrentCash,
		arg.OpenItem,
		arg.ID,
	)
	return err
}

const upsertAccountName = `-- name: UpsertAccountName :exec
INSERT INTO account_names (account_id, lang, name)
VALUES (?, ?, ?)
ON CONFLICT (account_id, lang) DO UPDATE SET name = excluded.name
`

type UpsertAccountNameParams struct {
	AccountID int64
	Lang      string
	Name      string
}

// Insert or replace a single (account_id, lang) name. The store decides op
// (create first time / update thereafter) via GetAccountName before this runs.
func (q *Queries) UpsertAccountName(ctx context.Context, arg UpsertAccountNameParams) error {
	_, err := q.db.ExecContext(ctx, upsertAccountName, arg.AccountID, arg.Lang, arg.Name)
	return err
}
