// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budget_splits.sql

package sqlc

import (
	"context"
	"database/sql"

	"cuento/internal/ids"
)

const deleteBudgetPlan = `-- name: DeleteBudgetPlan :exec
DELETE FROM budget_plans
WHERE id = ?
`

// Hard delete of a budget plan. For op=delete the version row is captured BEFORE
// this runs (rule 14: the live row must still exist to snapshot).
func (q *Queries) DeleteBudgetPlan(ctx context.Context, id ids.BudgetPlanID) error {
	_, err := q.db.ExecContext(ctx, deleteBudgetPlan, id)
	return err
}

const deleteBudgetSplit = `-- name: DeleteBudgetSplit :exec
DELETE FROM budget_splits
WHERE id = ?
`

// Hard delete of a budget split. For op=delete the version row is captured BEFORE
// this runs (rule 14: the live row must still exist to snapshot).
func (q *Queries) DeleteBudgetSplit(ctx context.Context, id ids.BudgetSplitID) error {
	_, err := q.db.ExecContext(ctx, deleteBudgetSplit, id)
	return err
}

const getBudgetPlan = `-- name: GetBudgetPlan :one
SELECT id, name, subsidiary_id, notes
FROM budget_plans
WHERE id = ?
`

func (q *Queries) GetBudgetPlan(ctx context.Context, id ids.BudgetPlanID) (BudgetPlan, error) {
	row := q.db.QueryRowContext(ctx, getBudgetPlan, id)
	var i BudgetPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SubsidiaryID,
		&i.Notes,
	)
	return i, err
}

const getBudgetSplit = `-- name: GetBudgetSplit :one
SELECT id, plan_id, description, date, account_id, fund_id, program_id, amount, currency
FROM budget_splits
WHERE id = ?
`

func (q *Queries) GetBudgetSplit(ctx context.Context, id ids.BudgetSplitID) (BudgetSplit, error) {
	row := q.db.QueryRowContext(ctx, getBudgetSplit, id)
	var i BudgetSplit
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Description,
		&i.Date,
		&i.AccountID,
		&i.FundID,
		&i.ProgramID,
		&i.Amount,
		&i.Currency,
	)
	return i, err
}

const insertBudgetPlan = `-- name: InsertBudgetPlan :one

INSERT INTO budget_plans (name, subsidiary_id, notes)
VALUES (?, ?, ?)
RETURNING id
`

type InsertBudgetPlanParams struct {
	Name         string
	SubsidiaryID ids.SubsidiaryID
	Notes        string
}

// ===========================================================================
// budget_plans
// ===========================================================================
// Live insert of a budget plan. Returns the new id for the store to snapshot.
func (q *Queries) InsertBudgetPlan(ctx context.Context, arg InsertBudgetPlanParams) (ids.BudgetPlanID, error) {
	row := q.db.QueryRowContext(ctx, insertBudgetPlan, arg.Name, arg.SubsidiaryID, arg.Notes)
	var id ids.BudgetPlanID
	err := row.Scan(&id)
	return id, err
}

const insertBudgetPlanVersion = `-- name: InsertBudgetPlanVersion :exec
INSERT INTO budget_plans_versions
  (entity_id, change_id, valid_from, op, name, subsidiary_id, notes)
SELECT bp.id, c.id, c.at, ?, bp.name, bp.subsidiary_id, bp.notes
FROM budget_plans bp, changes c
WHERE c.id = ? AND bp.id = ?
`

type InsertBudgetPlanVersionParams struct {
	Op   string
	ID   ids.ChangeID     // change_id
	ID_2 ids.BudgetPlanID // entity_id (budget_plans.id)
}

// Snapshot-from-live version append for budget_plans (single-column entity). For
// op='create'/'update' runs AFTER the live write; for op='delete' runs BEFORE the
// live delete. Params (positional): op, change_id, entity_id.
func (q *Queries) InsertBudgetPlanVersion(ctx context.Context, arg InsertBudgetPlanVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertBudgetPlanVersion, arg.Op, arg.ID, arg.ID_2)
	return err
}

const insertBudgetSplit = `-- name: InsertBudgetSplit :one

INSERT INTO budget_splits
  (plan_id, description, date, account_id, fund_id, program_id, amount, currency)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertBudgetSplitParams struct {
	PlanID      ids.BudgetPlanID
	Description string
	Date        string
	AccountID   ids.AccountID
	FundID      sql.NullInt64
	ProgramID   sql.NullInt64
	Amount      int64
	Currency    string
}

// ===========================================================================
// budget_splits
// ===========================================================================
// Live insert of a budget split. amount is minor units, SIGNED (rule 3); fund_id
// may be NULL (unrestricted); program_id is NULL only on A/L legs. The store
// validates the account (leaf in the plan's subsidiary; R/E or open_item A/L), the
// fund/program refs+scope, and the program-required/forbidden rule. Returns the id.
func (q *Queries) InsertBudgetSplit(ctx context.Context, arg InsertBudgetSplitParams) (ids.BudgetSplitID, error) {
	row := q.db.QueryRowContext(
		ctx, insertBudgetSplit,
		arg.PlanID,
		arg.Description,
		arg.Date,
		arg.AccountID,
		arg.FundID,
		arg.ProgramID,
		arg.Amount,
		arg.Currency,
	)
	var id ids.BudgetSplitID
	err := row.Scan(&id)
	return id, err
}

const insertBudgetSplitVersion = `-- name: InsertBudgetSplitVersion :exec
INSERT INTO budget_splits_versions
  (entity_id, change_id, valid_from, op, plan_id, description, date, account_id,
   fund_id, program_id, amount, currency)
SELECT bs.id, c.id, c.at, ?, bs.plan_id, bs.description, bs.date, bs.account_id,
       bs.fund_id, bs.program_id, bs.amount, bs.currency
FROM budget_splits bs, changes c
WHERE c.id = ? AND bs.id = ?
`

type InsertBudgetSplitVersionParams struct {
	Op   string
	ID   ids.ChangeID      // change_id
	ID_2 ids.BudgetSplitID // entity_id (budget_splits.id)
}

// Snapshot-from-live version append for budget_splits (single-column entity). For
// op='create'/'update' runs AFTER the live write; for op='delete' runs BEFORE the
// live delete. Params (positional): op, change_id, entity_id.
func (q *Queries) InsertBudgetSplitVersion(ctx context.Context, arg InsertBudgetSplitVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertBudgetSplitVersion, arg.Op, arg.ID, arg.ID_2)
	return err
}

const listBudgetPlans = `-- name: ListBudgetPlans :many
SELECT id, name, subsidiary_id, notes
FROM budget_plans
ORDER BY id
`

func (q *Queries) ListBudgetPlans(ctx context.Context) ([]BudgetPlan, error) {
	rows, err := q.db.QueryContext(ctx, listBudgetPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BudgetPlan
	for rows.Next() {
		var i BudgetPlan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SubsidiaryID,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetSplits = `-- name: ListBudgetSplits :many
SELECT id, plan_id, description, date, account_id, fund_id, program_id, amount, currency
FROM budget_splits
WHERE plan_id = ?
ORDER BY date, id
`

// The splits of one plan, date-then-id-ordered (the plan editor + p27.3 report
// source).
func (q *Queries) ListBudgetSplits(ctx context.Context, planID ids.BudgetPlanID) ([]BudgetSplit, error) {
	rows, err := q.db.QueryContext(ctx, listBudgetSplits, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BudgetSplit
	for rows.Next() {
		var i BudgetSplit
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Description,
			&i.Date,
			&i.AccountID,
			&i.FundID,
			&i.ProgramID,
			&i.Amount,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBudgetPlan = `-- name: UpdateBudgetPlan :exec
UPDATE budget_plans
SET name = ?, subsidiary_id = ?, notes = ?
WHERE id = ?
`

type UpdateBudgetPlanParams struct {
	Name         string
	SubsidiaryID ids.SubsidiaryID
	Notes        string
	ID           ids.BudgetPlanID
}

func (q *Queries) UpdateBudgetPlan(ctx context.Context, arg UpdateBudgetPlanParams) error {
	_, err := q.db.ExecContext(
		ctx, updateBudgetPlan,
		arg.Name,
		arg.SubsidiaryID,
		arg.Notes,
		arg.ID,
	)
	return err
}

const updateBudgetSplit = `-- name: UpdateBudgetSplit :exec
UPDATE budget_splits
SET description = ?, date = ?, account_id = ?, fund_id = ?, program_id = ?,
    amount = ?, currency = ?
WHERE id = ?
`

type UpdateBudgetSplitParams struct {
	Description string
	Date        string
	AccountID   ids.AccountID
	FundID      sql.NullInt64
	ProgramID   sql.NullInt64
	Amount      int64
	Currency    string
	ID          ids.BudgetSplitID
}

func (q *Queries) UpdateBudgetSplit(ctx context.Context, arg UpdateBudgetSplitParams) error {
	_, err := q.db.ExecContext(
		ctx, updateBudgetSplit,
		arg.Description,
		arg.Date,
		arg.AccountID,
		arg.FundID,
		arg.ProgramID,
		arg.Amount,
		arg.Currency,
		arg.ID,
	)
	return err
}
