// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budgets.sql

package sqlc

import (
	"context"
	"database/sql"
)

const budgetScheduleDates = `-- name: BudgetScheduleDates :many
SELECT occurs_on FROM budget_schedule_dates
WHERE schedule_id = ?
ORDER BY occurs_on
`

// The imported date list for a schedule (order-insensitive; the store builds a set
// for the diff and the engine sorts).
func (q *Queries) BudgetScheduleDates(ctx context.Context, scheduleID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, budgetScheduleDates, scheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var occurs_on string
		if err := rows.Scan(&occurs_on); err != nil {
			return nil, err
		}
		items = append(items, occurs_on)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteBudgetLine = `-- name: DeleteBudgetLine :exec
DELETE FROM budget_lines
WHERE id = ?
`

// Hard delete of a budget line. For op=delete the version row is captured BEFORE
// this runs (rule 14: everything but transactions hard-deletes with an audit
// version; the live row must still exist to snapshot).
func (q *Queries) DeleteBudgetLine(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBudgetLine, id)
	return err
}

const deleteBudgetScheduleDate = `-- name: DeleteBudgetScheduleDate :exec
DELETE FROM budget_schedule_dates
WHERE schedule_id = ? AND occurs_on = ?
`

type DeleteBudgetScheduleDateParams struct {
	ScheduleID int64
	OccursOn   string
}

// Remove one imported date. For op=delete the version row is captured BEFORE this
// runs (the live row must still exist to snapshot).
func (q *Queries) DeleteBudgetScheduleDate(ctx context.Context, arg DeleteBudgetScheduleDateParams) error {
	_, err := q.db.ExecContext(ctx, deleteBudgetScheduleDate, arg.ScheduleID, arg.OccursOn)
	return err
}

const getBudget = `-- name: GetBudget :one
SELECT id, name, period_start, period_end, notes
FROM budgets
WHERE id = ?
`

func (q *Queries) GetBudget(ctx context.Context, id int64) (Budget, error) {
	row := q.db.QueryRowContext(ctx, getBudget, id)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Notes,
	)
	return i, err
}

const getBudgetLine = `-- name: GetBudgetLine :one
SELECT id, budget_id, subsidiary_id, account_id, fund_id, program_id, amount,
       currency, schedule_id
FROM budget_lines
WHERE id = ?
`

func (q *Queries) GetBudgetLine(ctx context.Context, id int64) (BudgetLine, error) {
	row := q.db.QueryRowContext(ctx, getBudgetLine, id)
	var i BudgetLine
	err := row.Scan(
		&i.ID,
		&i.BudgetID,
		&i.SubsidiaryID,
		&i.AccountID,
		&i.FundID,
		&i.ProgramID,
		&i.Amount,
		&i.Currency,
		&i.ScheduleID,
	)
	return i, err
}

const getBudgetSchedule = `-- name: GetBudgetSchedule :one
SELECT id, name, kind, day_of_month, day_of_month_2, ordinal, weekday,
       anchor_date, weekend_adjust, notes
FROM budget_schedules
WHERE id = ?
`

func (q *Queries) GetBudgetSchedule(ctx context.Context, id int64) (BudgetSchedule, error) {
	row := q.db.QueryRowContext(ctx, getBudgetSchedule, id)
	var i BudgetSchedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.DayOfMonth,
		&i.DayOfMonth2,
		&i.Ordinal,
		&i.Weekday,
		&i.AnchorDate,
		&i.WeekendAdjust,
		&i.Notes,
	)
	return i, err
}

const insertBudget = `-- name: InsertBudget :one

INSERT INTO budgets (name, period_start, period_end, notes)
VALUES (?, ?, ?, ?)
RETURNING id
`

type InsertBudgetParams struct {
	Name        string
	PeriodStart string
	PeriodEnd   string
	Notes       string
}

// ===========================================================================
// budgets
// ===========================================================================
func (q *Queries) InsertBudget(ctx context.Context, arg InsertBudgetParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertBudget,
		arg.Name,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Notes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertBudgetLine = `-- name: InsertBudgetLine :one

INSERT INTO budget_lines
  (budget_id, subsidiary_id, account_id, fund_id, program_id, amount, currency,
   schedule_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertBudgetLineParams struct {
	BudgetID     int64
	SubsidiaryID int64
	AccountID    int64
	FundID       sql.NullInt64
	ProgramID    int64
	Amount       int64
	Currency     string
	ScheduleID   int64
}

// ===========================================================================
// budget_lines
// ===========================================================================
// Live insert of a budget line. amount is minor units per occurrence (rule 3);
// fund_id may be NULL (unrestricted); the store validates the R/E account, the
// fund/program/sub/schedule refs, and the currency. Returns the new id.
func (q *Queries) InsertBudgetLine(ctx context.Context, arg InsertBudgetLineParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertBudgetLine,
		arg.BudgetID,
		arg.SubsidiaryID,
		arg.AccountID,
		arg.FundID,
		arg.ProgramID,
		arg.Amount,
		arg.Currency,
		arg.ScheduleID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertBudgetLineVersion = `-- name: InsertBudgetLineVersion :exec
INSERT INTO budget_lines_versions
  (entity_id, change_id, valid_from, op, budget_id, subsidiary_id, account_id,
   fund_id, program_id, amount, currency, schedule_id)
SELECT bl.id, c.id, c.at, ?, bl.budget_id, bl.subsidiary_id, bl.account_id,
       bl.fund_id, bl.program_id, bl.amount, bl.currency, bl.schedule_id
FROM budget_lines bl, changes c
WHERE c.id = ? AND bl.id = ?
`

type InsertBudgetLineVersionParams struct {
	Op   string
	ID   int64
	ID_2 int64
}

// Snapshot-from-live version append for budget_lines (single-column entity). For
// op='create'/'update' runs AFTER the live write; for op='delete' runs BEFORE the
// live delete. Params (positional): op, change_id, entity_id.
func (q *Queries) InsertBudgetLineVersion(ctx context.Context, arg InsertBudgetLineVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertBudgetLineVersion, arg.Op, arg.ID, arg.ID_2)
	return err
}

const insertBudgetSchedule = `-- name: InsertBudgetSchedule :one


INSERT INTO budget_schedules
  (name, kind, day_of_month, day_of_month_2, ordinal, weekday, anchor_date,
   weekend_adjust, notes)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertBudgetScheduleParams struct {
	Name          string
	Kind          string
	DayOfMonth    sql.NullInt64
	DayOfMonth2   sql.NullInt64
	Ordinal       sql.NullInt64
	Weekday       sql.NullInt64
	AnchorDate    sql.NullString
	WeekendAdjust string
	Notes         string
}

// p19.1: budget operations (Phase 19 budgeting). All SQL for the store's budget
// methods lives here (rule 6). Copies the version-append convention established in
// funds.sql (p07.3): the entity op does the live write inside the funnel's fn, then
// appends a snapshot-from-live version row, so each version row is byte-identical to
// its live row (Z3 can never diverge) and valid_from == changes.at BY CONSTRUCTION.
//
// budget_schedule_dates is a COMPOSITE (schedule_id, occurs_on) SET, versioned like
// fund_subsidiaries: an import is op='create', a removal op='delete' (captured
// BEFORE the live DELETE -- the removal-op ordering).
//
// Query names are DISTINCT from every other domain's (InsertBudget vs InsertFund,
// ...): sqlc emits into one package, so a name collision fails generation.
//
// NOTE: keep every comment and identifier in this file PURE ASCII. sqlc v1.31.1
// miscounts byte offsets when a query file contains multi-byte UTF-8, corrupting
// the generated SQL for the WHOLE file (see docs/DECISIONS.md p04.2). Version
// params use plain positional `?` (the append-query convention).
// ===========================================================================
// budget_schedules
// ===========================================================================
// Live insert of a named schedule. kind is a CHECK enum; the kind-specific fields
// are validated in the store per kind. Returns the new id for the store to
// snapshot + return.
func (q *Queries) InsertBudgetSchedule(ctx context.Context, arg InsertBudgetScheduleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertBudgetSchedule,
		arg.Name,
		arg.Kind,
		arg.DayOfMonth,
		arg.DayOfMonth2,
		arg.Ordinal,
		arg.Weekday,
		arg.AnchorDate,
		arg.WeekendAdjust,
		arg.Notes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertBudgetScheduleDate = `-- name: InsertBudgetScheduleDate :exec
INSERT INTO budget_schedule_dates (schedule_id, occurs_on)
VALUES (?, ?)
`

type InsertBudgetScheduleDateParams struct {
	ScheduleID int64
	OccursOn   string
}

// Import one (schedule_id, occurs_on) date. The list is a SET (the PK forbids
// duplicates); callers dedupe before adding.
func (q *Queries) InsertBudgetScheduleDate(ctx context.Context, arg InsertBudgetScheduleDateParams) error {
	_, err := q.db.ExecContext(ctx, insertBudgetScheduleDate, arg.ScheduleID, arg.OccursOn)
	return err
}

const insertBudgetScheduleDateVersion = `-- name: InsertBudgetScheduleDateVersion :exec
INSERT INTO budget_schedule_dates_versions
  (entity_id, change_id, valid_from, op, occurs_on)
SELECT bsd.schedule_id, c.id, c.at, ?, bsd.occurs_on
FROM budget_schedule_dates bsd, changes c
WHERE c.id = ? AND bsd.schedule_id = ? AND bsd.occurs_on = ?
`

type InsertBudgetScheduleDateVersionParams struct {
	Op         string
	ID         int64
	ScheduleID int64
	OccursOn   string
}

// Snapshot-from-live version append for a COMPOSITE (schedule_id, occurs_on) list
// row. entity_id = schedule_id; occurs_on is both a snapshot column and part of the
// entity identity (00016). For op='create' this runs AFTER the live insert; for
// op='delete' it runs BEFORE the live delete. Params (positional): op, change_id,
// schedule_id, occurs_on -> Op, ID, ScheduleID, OccursOn.
func (q *Queries) InsertBudgetScheduleDateVersion(ctx context.Context, arg InsertBudgetScheduleDateVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertBudgetScheduleDateVersion,
		arg.Op,
		arg.ID,
		arg.ScheduleID,
		arg.OccursOn,
	)
	return err
}

const insertBudgetScheduleVersion = `-- name: InsertBudgetScheduleVersion :exec
INSERT INTO budget_schedules_versions
  (entity_id, change_id, valid_from, op, name, kind, day_of_month, day_of_month_2,
   ordinal, weekday, anchor_date, weekend_adjust, notes)
SELECT bs.id, c.id, c.at, ?, bs.name, bs.kind, bs.day_of_month, bs.day_of_month_2,
       bs.ordinal, bs.weekday, bs.anchor_date, bs.weekend_adjust, bs.notes
FROM budget_schedules bs, changes c
WHERE c.id = ? AND bs.id = ?
`

type InsertBudgetScheduleVersionParams struct {
	Op   string
	ID   int64
	ID_2 int64
}

// Snapshot-from-live version append for budget_schedules (STANDARD single-column
// entity). Reads the CURRENT live row (MUST run AFTER the live write) and copies
// every business column, so the version row is byte-identical to the live row;
// valid_from is the change's own `at`. Snapshot column set matches 00016 exactly.
// Params (positional): op, change_id, entity_id -> Op, ID (change_id), ID_2.
func (q *Queries) InsertBudgetScheduleVersion(ctx context.Context, arg InsertBudgetScheduleVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertBudgetScheduleVersion, arg.Op, arg.ID, arg.ID_2)
	return err
}

const insertBudgetVersion = `-- name: InsertBudgetVersion :exec
INSERT INTO budgets_versions
  (entity_id, change_id, valid_from, op, name, period_start, period_end, notes)
SELECT b.id, c.id, c.at, ?, b.name, b.period_start, b.period_end, b.notes
FROM budgets b, changes c
WHERE c.id = ? AND b.id = ?
`

type InsertBudgetVersionParams struct {
	Op   string
	ID   int64
	ID_2 int64
}

// Snapshot-from-live version append for budgets (single-column entity). Runs AFTER
// the live write. Params (positional): op, change_id, entity_id.
func (q *Queries) InsertBudgetVersion(ctx context.Context, arg InsertBudgetVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertBudgetVersion, arg.Op, arg.ID, arg.ID_2)
	return err
}

const listBudgetLines = `-- name: ListBudgetLines :many
SELECT id, budget_id, subsidiary_id, account_id, fund_id, program_id, amount,
       currency, schedule_id
FROM budget_lines
WHERE budget_id = ?
ORDER BY id
`

// The lines of one budget, id-ordered (the budget editor + p19.2 expansion source).
func (q *Queries) ListBudgetLines(ctx context.Context, budgetID int64) ([]BudgetLine, error) {
	rows, err := q.db.QueryContext(ctx, listBudgetLines, budgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BudgetLine
	for rows.Next() {
		var i BudgetLine
		if err := rows.Scan(
			&i.ID,
			&i.BudgetID,
			&i.SubsidiaryID,
			&i.AccountID,
			&i.FundID,
			&i.ProgramID,
			&i.Amount,
			&i.Currency,
			&i.ScheduleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetSchedules = `-- name: ListBudgetSchedules :many
SELECT id, name, kind, day_of_month, day_of_month_2, ordinal, weekday,
       anchor_date, weekend_adjust, notes
FROM budget_schedules
ORDER BY id
`

// Every schedule, id-ordered (the library list + line editor option source, p19.3).
func (q *Queries) ListBudgetSchedules(ctx context.Context) ([]BudgetSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listBudgetSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BudgetSchedule
	for rows.Next() {
		var i BudgetSchedule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.DayOfMonth,
			&i.DayOfMonth2,
			&i.Ordinal,
			&i.Weekday,
			&i.AnchorDate,
			&i.WeekendAdjust,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgets = `-- name: ListBudgets :many
SELECT id, name, period_start, period_end, notes
FROM budgets
ORDER BY id
`

func (q *Queries) ListBudgets(ctx context.Context) ([]Budget, error) {
	rows, err := q.db.QueryContext(ctx, listBudgets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Budget
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBudget = `-- name: UpdateBudget :exec
UPDATE budgets
SET name = ?, period_start = ?, period_end = ?, notes = ?
WHERE id = ?
`

type UpdateBudgetParams struct {
	Name        string
	PeriodStart string
	PeriodEnd   string
	Notes       string
	ID          int64
}

func (q *Queries) UpdateBudget(ctx context.Context, arg UpdateBudgetParams) error {
	_, err := q.db.ExecContext(ctx, updateBudget,
		arg.Name,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Notes,
		arg.ID,
	)
	return err
}

const updateBudgetLine = `-- name: UpdateBudgetLine :exec
UPDATE budget_lines
SET budget_id = ?, subsidiary_id = ?, account_id = ?, fund_id = ?, program_id = ?,
    amount = ?, currency = ?, schedule_id = ?
WHERE id = ?
`

type UpdateBudgetLineParams struct {
	BudgetID     int64
	SubsidiaryID int64
	AccountID    int64
	FundID       sql.NullInt64
	ProgramID    int64
	Amount       int64
	Currency     string
	ScheduleID   int64
	ID           int64
}

func (q *Queries) UpdateBudgetLine(ctx context.Context, arg UpdateBudgetLineParams) error {
	_, err := q.db.ExecContext(ctx, updateBudgetLine,
		arg.BudgetID,
		arg.SubsidiaryID,
		arg.AccountID,
		arg.FundID,
		arg.ProgramID,
		arg.Amount,
		arg.Currency,
		arg.ScheduleID,
		arg.ID,
	)
	return err
}

const updateBudgetSchedule = `-- name: UpdateBudgetSchedule :exec
UPDATE budget_schedules
SET name = ?, kind = ?, day_of_month = ?, day_of_month_2 = ?, ordinal = ?,
    weekday = ?, anchor_date = ?, weekend_adjust = ?, notes = ?
WHERE id = ?
`

type UpdateBudgetScheduleParams struct {
	Name          string
	Kind          string
	DayOfMonth    sql.NullInt64
	DayOfMonth2   sql.NullInt64
	Ordinal       sql.NullInt64
	Weekday       sql.NullInt64
	AnchorDate    sql.NullString
	WeekendAdjust string
	Notes         string
	ID            int64
}

// Live update: the store reads the current row (GetBudgetSchedule), overrides the
// caller's fields, and writes the full desired state here (snapshot-from-live).
func (q *Queries) UpdateBudgetSchedule(ctx context.Context, arg UpdateBudgetScheduleParams) error {
	_, err := q.db.ExecContext(ctx, updateBudgetSchedule,
		arg.Name,
		arg.Kind,
		arg.DayOfMonth,
		arg.DayOfMonth2,
		arg.Ordinal,
		arg.Weekday,
		arg.AnchorDate,
		arg.WeekendAdjust,
		arg.Notes,
		arg.ID,
	)
	return err
}
