// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: changes.sql

package sqlc

import (
	"context"
	"database/sql"

	"cuento/internal/ids"
)

const countChanges = `-- name: CountChanges :one
SELECT COUNT(*) FROM changes
`

func (q *Queries) CountChanges(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChanges)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getChange = `-- name: GetChange :one
SELECT id, actor_id, at, kind, note
FROM changes
WHERE id = ?
`

func (q *Queries) GetChange(ctx context.Context, id ids.ChangeID) (Change, error) {
	row := q.db.QueryRowContext(ctx, getChange, id)
	var i Change
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.At,
		&i.Kind,
		&i.Note,
	)
	return i, err
}

const insertChange = `-- name: InsertChange :one
INSERT INTO changes (actor_id, at, kind, note)
VALUES (?, ?, ?, ?)
RETURNING id
`

type InsertChangeParams struct {
	ActorID int64
	At      string
	Kind    string
	Note    sql.NullString
}

func (q *Queries) InsertChange(ctx context.Context, arg InsertChangeParams) (ids.ChangeID, error) {
	row := q.db.QueryRowContext(ctx, insertChange,
		arg.ActorID,
		arg.At,
		arg.Kind,
		arg.Note,
	)
	var id ids.ChangeID
	err := row.Scan(&id)
	return id, err
}
