// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: currencies.sql

package sqlc

import (
	"context"
)

const getCurrency = `-- name: GetCurrency :one
SELECT code, exponent, symbol, name, active
FROM currencies
WHERE code = ?
`

func (q *Queries) GetCurrency(ctx context.Context, code string) (Currency, error) {
	row := q.db.QueryRowContext(ctx, getCurrency, code)
	var i Currency
	err := row.Scan(
		&i.Code,
		&i.Exponent,
		&i.Symbol,
		&i.Name,
		&i.Active,
	)
	return i, err
}

const listCurrencies = `-- name: ListCurrencies :many
SELECT code, exponent, symbol, name, active
FROM currencies
ORDER BY code
`

// ORDER BY code for deterministic output (tests key by code, not order).
func (q *Queries) ListCurrencies(ctx context.Context) ([]Currency, error) {
	rows, err := q.db.QueryContext(ctx, listCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Currency
	for rows.Next() {
		var i Currency
		if err := rows.Scan(
			&i.Code,
			&i.Exponent,
			&i.Symbol,
			&i.Name,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
