// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expense_reports.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countExpenseReportLines = `-- name: CountExpenseReportLines :one
SELECT COUNT(*) FROM expense_report_lines WHERE report_id = ?
`

// Count of a report's lines (the submit guard requires >= 1 line).
func (q *Queries) CountExpenseReportLines(ctx context.Context, reportID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countExpenseReportLines, reportID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpenseReport = `-- name: DeleteExpenseReport :exec
DELETE FROM expense_reports
WHERE id = ?
`

// Hard delete of a DRAFT report (p25.3 discard). Its lines are deleted first (each with
// an op=delete version); for op=delete the report's own version row is captured BEFORE
// this runs (rule 14: the live row must still exist to snapshot).
func (q *Queries) DeleteExpenseReport(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpenseReport, id)
	return err
}

const deleteExpenseReportLine = `-- name: DeleteExpenseReportLine :exec
DELETE FROM expense_report_lines
WHERE id = ?
`

// Hard delete of a report line. For op=delete the version row is captured BEFORE
// this runs (rule 14: everything but transactions hard-deletes with an audit
// version; the live row must still exist to snapshot).
func (q *Queries) DeleteExpenseReportLine(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpenseReportLine, id)
	return err
}

const getExpenseReport = `-- name: GetExpenseReport :one
SELECT id, submitter_id, subsidiary_id, status, review_notes,
       posted_transaction_id, created_at
FROM expense_reports
WHERE id = ?
`

func (q *Queries) GetExpenseReport(ctx context.Context, id int64) (ExpenseReport, error) {
	row := q.db.QueryRowContext(ctx, getExpenseReport, id)
	var i ExpenseReport
	err := row.Scan(
		&i.ID,
		&i.SubmitterID,
		&i.SubsidiaryID,
		&i.Status,
		&i.ReviewNotes,
		&i.PostedTransactionID,
		&i.CreatedAt,
	)
	return i, err
}

const getExpenseReportLine = `-- name: GetExpenseReportLine :one
SELECT id, report_id, account_id, amount, fund_id, program_id, memo
FROM expense_report_lines
WHERE id = ?
`

func (q *Queries) GetExpenseReportLine(ctx context.Context, id int64) (ExpenseReportLine, error) {
	row := q.db.QueryRowContext(ctx, getExpenseReportLine, id)
	var i ExpenseReportLine
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.AccountID,
		&i.Amount,
		&i.FundID,
		&i.ProgramID,
		&i.Memo,
	)
	return i, err
}

const insertExpenseReport = `-- name: InsertExpenseReport :one


INSERT INTO expense_reports (submitter_id, subsidiary_id, created_at)
VALUES (?, ?, ?)
RETURNING id
`

type InsertExpenseReportParams struct {
	SubmitterID  int64
	SubsidiaryID int64
	CreatedAt    string
}

// p20.1: expense-report operations (Phase 20). All SQL for the store's
// expense-report methods lives here (rule 6). Copies the version-append convention
// established in funds.sql/budgets.sql: the entity op does the live write inside the
// funnel's fn, then appends a snapshot-from-live version row, so each version row is
// byte-identical to its live row (Z3 can never diverge) and valid_from == changes.at
// BY CONSTRUCTION.
//
// Query names are DISTINCT from every other domain's (sqlc emits into one package, so
// a name collision fails generation). Version params use plain positional `?` (the
// append-query convention).
//
// NOTE: keep every comment and identifier in this file PURE ASCII. sqlc v1.31.1
// miscounts byte offsets when a query file contains multi-byte UTF-8, corrupting the
// generated SQL for the WHOLE file (see docs/DECISIONS.md p04.2).
// ===========================================================================
// expense_reports
// ===========================================================================
// Live insert of a report header (status defaults to 'draft'). created_at is the
// store's clock. posted_transaction_id starts NULL (set only on convert). Returns
// the new id for the store to snapshot + return.
func (q *Queries) InsertExpenseReport(ctx context.Context, arg InsertExpenseReportParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertExpenseReport, arg.SubmitterID, arg.SubsidiaryID, arg.CreatedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertExpenseReportLine = `-- name: InsertExpenseReportLine :one

INSERT INTO expense_report_lines (report_id, account_id, amount, fund_id, program_id, memo)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertExpenseReportLineParams struct {
	ReportID  int64
	AccountID int64
	Amount    int64
	FundID    sql.NullInt64
	ProgramID sql.NullInt64
	Memo      string
}

// ===========================================================================
// expense_report_lines
// ===========================================================================
// Live insert of a report line. amount is minor units, SIGNED (rule 3; the report
// need not balance). fund_id/program_id may be NULL (the reviewer resolves them at
// convert). Returns the new id.
func (q *Queries) InsertExpenseReportLine(ctx context.Context, arg InsertExpenseReportLineParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertExpenseReportLine,
		arg.ReportID,
		arg.AccountID,
		arg.Amount,
		arg.FundID,
		arg.ProgramID,
		arg.Memo,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertExpenseReportLineVersion = `-- name: InsertExpenseReportLineVersion :exec
INSERT INTO expense_report_lines_versions
  (entity_id, change_id, valid_from, op, report_id, account_id, amount, fund_id,
   program_id, memo)
SELECT erl.id, c.id, c.at, ?, erl.report_id, erl.account_id, erl.amount,
       erl.fund_id, erl.program_id, erl.memo
FROM expense_report_lines erl, changes c
WHERE c.id = ? AND erl.id = ?
`

type InsertExpenseReportLineVersionParams struct {
	Op   string
	ID   int64
	ID_2 int64
}

// Snapshot-from-live version append for expense_report_lines (single-column
// entity). For op='create'/'update' runs AFTER the live write; for op='delete' runs
// BEFORE the live delete. Params (positional): op, change_id, entity_id.
func (q *Queries) InsertExpenseReportLineVersion(ctx context.Context, arg InsertExpenseReportLineVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertExpenseReportLineVersion, arg.Op, arg.ID, arg.ID_2)
	return err
}

const insertExpenseReportVersion = `-- name: InsertExpenseReportVersion :exec
INSERT INTO expense_reports_versions
  (entity_id, change_id, valid_from, op, submitter_id, subsidiary_id, status,
   review_notes, posted_transaction_id, created_at)
SELECT er.id, c.id, c.at, ?, er.submitter_id, er.subsidiary_id, er.status,
       er.review_notes, er.posted_transaction_id, er.created_at
FROM expense_reports er, changes c
WHERE c.id = ? AND er.id = ?
`

type InsertExpenseReportVersionParams struct {
	Op   string
	ID   int64
	ID_2 int64
}

// Snapshot-from-live version append for expense_reports (STANDARD single-column
// entity). Reads the CURRENT live row (MUST run AFTER the live write) and copies
// every business column, so the version row is byte-identical to the live row;
// valid_from is the change's own `at`. Snapshot column set matches 00017 exactly.
// Params (positional): op, change_id, entity_id -> Op, ID (change_id), ID_2.
func (q *Queries) InsertExpenseReportVersion(ctx context.Context, arg InsertExpenseReportVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertExpenseReportVersion, arg.Op, arg.ID, arg.ID_2)
	return err
}

const listExpenseReportLines = `-- name: ListExpenseReportLines :many
SELECT id, report_id, account_id, amount, fund_id, program_id, memo
FROM expense_report_lines
WHERE report_id = ?
ORDER BY id
`

// The lines of one report, id-ordered (the editor + the p20.3 convert prefill).
func (q *Queries) ListExpenseReportLines(ctx context.Context, reportID int64) ([]ExpenseReportLine, error) {
	rows, err := q.db.QueryContext(ctx, listExpenseReportLines, reportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseReportLine
	for rows.Next() {
		var i ExpenseReportLine
		if err := rows.Scan(
			&i.ID,
			&i.ReportID,
			&i.AccountID,
			&i.Amount,
			&i.FundID,
			&i.ProgramID,
			&i.Memo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseReportsByStatus = `-- name: ListExpenseReportsByStatus :many
SELECT id, submitter_id, subsidiary_id, status, review_notes,
       posted_transaction_id, created_at
FROM expense_reports
WHERE status = ?
ORDER BY id
`

// Reports in a given status, id-ordered (the p20.3 reviewer queue reads 'submitted').
func (q *Queries) ListExpenseReportsByStatus(ctx context.Context, status string) ([]ExpenseReport, error) {
	rows, err := q.db.QueryContext(ctx, listExpenseReportsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseReport
	for rows.Next() {
		var i ExpenseReport
		if err := rows.Scan(
			&i.ID,
			&i.SubmitterID,
			&i.SubsidiaryID,
			&i.Status,
			&i.ReviewNotes,
			&i.PostedTransactionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseReportsBySubmitter = `-- name: ListExpenseReportsBySubmitter :many
SELECT id, submitter_id, subsidiary_id, status, review_notes,
       posted_transaction_id, created_at
FROM expense_reports
WHERE submitter_id = ?
ORDER BY id DESC
`

// A submitter's own reports, newest first (the p20.2 my-reports list).
func (q *Queries) ListExpenseReportsBySubmitter(ctx context.Context, submitterID int64) ([]ExpenseReport, error) {
	rows, err := q.db.QueryContext(ctx, listExpenseReportsBySubmitter, submitterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseReport
	for rows.Next() {
		var i ExpenseReport
		if err := rows.Scan(
			&i.ID,
			&i.SubmitterID,
			&i.SubsidiaryID,
			&i.Status,
			&i.ReviewNotes,
			&i.PostedTransactionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setExpenseReportConverted = `-- name: SetExpenseReportConverted :exec
UPDATE expense_reports
SET status = 'converted', posted_transaction_id = ?
WHERE id = ?
`

type SetExpenseReportConvertedParams struct {
	PostedTransactionID sql.NullInt64
	ID                  int64
}

// Live update flipping a report to 'converted' and LINKING the posted transaction.
// posted_transaction_id is set ONLY here (convert is its sole writer). The store
// validates the txn exists and the report is 'submitted' first.
func (q *Queries) SetExpenseReportConverted(ctx context.Context, arg SetExpenseReportConvertedParams) error {
	_, err := q.db.ExecContext(ctx, setExpenseReportConverted, arg.PostedTransactionID, arg.ID)
	return err
}

const setExpenseReportStatus = `-- name: SetExpenseReportStatus :exec
UPDATE expense_reports
SET status = ?, review_notes = ?
WHERE id = ?
`

type SetExpenseReportStatusParams struct {
	Status      string
	ReviewNotes string
	ID          int64
}

// Live update of a report's status + review_notes (the state-machine transition).
// The store validates the transition first; this writes the resulting state. Both
// columns are set together so a reject stores its reason and a resubmit preserves it
// (the store passes the current notes through).
func (q *Queries) SetExpenseReportStatus(ctx context.Context, arg SetExpenseReportStatusParams) error {
	_, err := q.db.ExecContext(ctx, setExpenseReportStatus, arg.Status, arg.ReviewNotes, arg.ID)
	return err
}

const setExpenseReportSubsidiary = `-- name: SetExpenseReportSubsidiary :exec
UPDATE expense_reports
SET subsidiary_id = ?
WHERE id = ?
`

type SetExpenseReportSubsidiaryParams struct {
	SubsidiaryID int64
	ID           int64
}

// Live update of a draft report's subsidiary (p25.3: the submitter picks the sub on
// the report page, editable ONLY while the report has no lines -- the store guards the
// line-count precondition so a change can't orphan sub-scoped line accounts).
func (q *Queries) SetExpenseReportSubsidiary(ctx context.Context, arg SetExpenseReportSubsidiaryParams) error {
	_, err := q.db.ExecContext(ctx, setExpenseReportSubsidiary, arg.SubsidiaryID, arg.ID)
	return err
}

const updateExpenseReportLine = `-- name: UpdateExpenseReportLine :exec
UPDATE expense_report_lines
SET account_id = ?, amount = ?, fund_id = ?, program_id = ?, memo = ?
WHERE id = ?
`

type UpdateExpenseReportLineParams struct {
	AccountID int64
	Amount    int64
	FundID    sql.NullInt64
	ProgramID sql.NullInt64
	Memo      string
	ID        int64
}

func (q *Queries) UpdateExpenseReportLine(ctx context.Context, arg UpdateExpenseReportLineParams) error {
	_, err := q.db.ExecContext(ctx, updateExpenseReportLine,
		arg.AccountID,
		arg.Amount,
		arg.FundID,
		arg.ProgramID,
		arg.Memo,
		arg.ID,
	)
	return err
}
