// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: import.sql

package sqlc

import (
	"context"
	"database/sql"

	"cuento/internal/ids"
)

const getImportBatch = `-- name: GetImportBatch :one
SELECT id, filename, account_id, subsidiary_id, profile_id, uploaded_by, uploaded_at
FROM import_batches WHERE id = ?
`

func (q *Queries) GetImportBatch(ctx context.Context, id ids.ImportBatchID) (ImportBatch, error) {
	row := q.db.QueryRowContext(ctx, getImportBatch, id)
	var i ImportBatch
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.AccountID,
		&i.SubsidiaryID,
		&i.ProfileID,
		&i.UploadedBy,
		&i.UploadedAt,
	)
	return i, err
}

const getImportRow = `-- name: GetImportRow :one
SELECT r.id, r.batch_id, r.account_id, r.raw_json, r.parsed_date, r.parsed_amount,
       r.parsed_payee, r.parsed_memo, r.status, r.dedupe_hash, r.posted_transaction_id,
       b.subsidiary_id AS subsidiary_id
FROM import_rows r
JOIN import_batches b ON b.id = r.batch_id
WHERE r.id = ?
`

type GetImportRowRow struct {
	ID                  ids.ImportRowID
	BatchID             ids.ImportBatchID
	AccountID           int64
	RawJson             string
	ParsedDate          sql.NullString
	ParsedAmount        sql.NullInt64
	ParsedPayee         sql.NullString
	ParsedMemo          sql.NullString
	Status              string
	DedupeHash          string
	PostedTransactionID sql.NullInt64
	SubsidiaryID        int64
}

// One staged row joined to its batch, for the p17.3 review queue (edit&post /
// discard). It carries the batch's subsidiary_id (the SUB the edit&post editor LOCKS)
// and the row's own account_id (denormalized from the batch = the bank side).
func (q *Queries) GetImportRow(ctx context.Context, id ids.ImportRowID) (GetImportRowRow, error) {
	row := q.db.QueryRowContext(ctx, getImportRow, id)
	var i GetImportRowRow
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.AccountID,
		&i.RawJson,
		&i.ParsedDate,
		&i.ParsedAmount,
		&i.ParsedPayee,
		&i.ParsedMemo,
		&i.Status,
		&i.DedupeHash,
		&i.PostedTransactionID,
		&i.SubsidiaryID,
	)
	return i, err
}

const getMappingProfile = `-- name: GetMappingProfile :one
SELECT id, name, config FROM mapping_profiles WHERE id = ?
`

func (q *Queries) GetMappingProfile(ctx context.Context, id ids.MappingProfileID) (MappingProfile, error) {
	row := q.db.QueryRowContext(ctx, getMappingProfile, id)
	var i MappingProfile
	err := row.Scan(&i.ID, &i.Name, &i.Config)
	return i, err
}

const importRowsByBatch = `-- name: ImportRowsByBatch :many
SELECT id, batch_id, account_id, raw_json, parsed_date, parsed_amount, parsed_payee,
       parsed_memo, status, dedupe_hash, posted_transaction_id
FROM import_rows
WHERE batch_id = ?
ORDER BY id
`

// Every staged row of a batch, in stage order -- the batch review list source.
func (q *Queries) ImportRowsByBatch(ctx context.Context, batchID ids.ImportBatchID) ([]ImportRow, error) {
	rows, err := q.db.QueryContext(ctx, importRowsByBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportRow
	for rows.Next() {
		var i ImportRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.AccountID,
			&i.RawJson,
			&i.ParsedDate,
			&i.ParsedAmount,
			&i.ParsedPayee,
			&i.ParsedMemo,
			&i.Status,
			&i.DedupeHash,
			&i.PostedTransactionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertImportBatch = `-- name: InsertImportBatch :one
INSERT INTO import_batches (filename, account_id, subsidiary_id, profile_id, uploaded_by, uploaded_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertImportBatchParams struct {
	Filename     string
	AccountID    int64
	SubsidiaryID int64
	ProfileID    ids.MappingProfileID
	UploadedBy   ids.UserID
	UploadedAt   string
}

// One upload, binding ONE account AND ONE subsidiary (the account-maps-to-subsidiary
// check is done in the store via HasAccountSubsidiaryMap before this runs).
func (q *Queries) InsertImportBatch(ctx context.Context, arg InsertImportBatchParams) (ids.ImportBatchID, error) {
	row := q.db.QueryRowContext(ctx, insertImportBatch,
		arg.Filename,
		arg.AccountID,
		arg.SubsidiaryID,
		arg.ProfileID,
		arg.UploadedBy,
		arg.UploadedAt,
	)
	var id ids.ImportBatchID
	err := row.Scan(&id)
	return id, err
}

const insertImportRow = `-- name: InsertImportRow :one
INSERT INTO import_rows
  (batch_id, account_id, raw_json, parsed_date, parsed_amount, parsed_payee, parsed_memo, status, dedupe_hash)
VALUES (?, ?, ?, ?, ?, ?, ?, 'pending', ?)
RETURNING id
`

type InsertImportRowParams struct {
	BatchID      ids.ImportBatchID
	AccountID    int64
	RawJson      string
	ParsedDate   sql.NullString
	ParsedAmount sql.NullInt64
	ParsedPayee  sql.NullString
	ParsedMemo   sql.NullString
	DedupeHash   string
}

// Stage one parsed row. account_id is denormalized from the batch (the dedupe
// scope, DECISIONS p17.1). status is 'pending'; dedupe_hash is precomputed in Go.
func (q *Queries) InsertImportRow(ctx context.Context, arg InsertImportRowParams) (ids.ImportRowID, error) {
	row := q.db.QueryRowContext(ctx, insertImportRow,
		arg.BatchID,
		arg.AccountID,
		arg.RawJson,
		arg.ParsedDate,
		arg.ParsedAmount,
		arg.ParsedPayee,
		arg.ParsedMemo,
		arg.DedupeHash,
	)
	var id ids.ImportRowID
	err := row.Scan(&id)
	return id, err
}

const insertMappingProfile = `-- name: InsertMappingProfile :one

INSERT INTO mapping_profiles (name, config)
VALUES (?, ?)
RETURNING id
`

type InsertMappingProfileParams struct {
	Name   string
	Config string
}

// p17.2: bank-CSV-import store SQL (upload + mapping + staging). All SQL for the
// import store methods lives here (rule 6). These three tables are NON-VERSIONED
// OPERATIONAL/STAGING tables (DECISIONS p17.1): like currencies/report_groups they
// have NO *_versions twin, so there is NO snapshot-from-live version append here.
// The mutations STILL run through the store write funnel (rule 2) -- one changes
// row anchors the tx boundary + actor -- exactly like PutRates and
// SetSplitReconciled; only the version-append step is skipped (no twin to write).
//
// The dedupe_hash = sha256(account|date|amount|normalized(payee+memo)) is computed
// in Go (internal/bankimport.DedupeHash); the SQL here only STORES it and provides
// the two LOOKUP sources a staging pass consults to FLAG (never enforce) a
// duplicate: (1) prior staged import_rows on the account, and (2) the natural keys
// of already-posted ledger splits on the account (re-derived in Go to the identical
// hash).
// Save a reusable CSV column-mapping. config is the opaque JSON blob the store
// encodes with encoding/json (the store owns the shape; the schema stores TEXT).
func (q *Queries) InsertMappingProfile(ctx context.Context, arg InsertMappingProfileParams) (ids.MappingProfileID, error) {
	row := q.db.QueryRowContext(ctx, insertMappingProfile, arg.Name, arg.Config)
	var id ids.MappingProfileID
	err := row.Scan(&id)
	return id, err
}

const ledgerSplitDedupeKeys = `-- name: LedgerSplitDedupeKeys :many
SELECT t.date        AS date,
       s.amount      AS amount,
       s.description AS description,
       s.memo        AS split_memo,
       t.memo        AS txn_memo
FROM splits s
JOIN transactions t ON t.id = s.transaction_id
WHERE s.account_id = ? AND t.deleted = 0
`

type LedgerSplitDedupeKeysRow struct {
	Date        string
	Amount      int64
	Description string
	SplitMemo   string
	TxnMemo     string
}

// Dedupe LOOKUP source (2): the natural keys of already-posted LEDGER splits on
// this account, on NON-DELETED transactions. Each row yields (date, amount,
// description, memo) which the store re-hashes in Go with bankimport.DedupeHash to
// the SAME hash a matching bank row would produce -- so a bank line that is already
// a posted transaction is flagged. The split MEMO is used, with the transaction
// memo as the fallback when the split memo is empty (documented in the store);
// description is the split's per-line free text (p26.20 -- it replaces the retired
// payee name; the bank-import write path sets it on the bank-account split).
func (q *Queries) LedgerSplitDedupeKeys(ctx context.Context, accountID int64) ([]LedgerSplitDedupeKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, ledgerSplitDedupeKeys, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerSplitDedupeKeysRow
	for rows.Next() {
		var i LedgerSplitDedupeKeysRow
		if err := rows.Scan(
			&i.Date,
			&i.Amount,
			&i.Description,
			&i.SplitMemo,
			&i.TxnMemo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deactivateMappingProfile = `-- name: DeactivateMappingProfile :execrows
UPDATE mapping_profiles SET active = 0 WHERE id = ? AND active = 1
`

// Soft-delete a saved profile: flip active to 0 so it drops out of the load list.
// No row is deleted (import_batches.profile_id keeps referencing it). Returns the
// affected row count so the store can distinguish a missing/already-gone profile.
func (q *Queries) DeactivateMappingProfile(ctx context.Context, id ids.MappingProfileID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deactivateMappingProfile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listMappingProfiles = `-- name: ListMappingProfiles :many
SELECT id, name, config FROM mapping_profiles WHERE active = 1 ORDER BY id DESC
`

// The saved profiles the mapping UI offers for reuse, newest first. Soft-deleted
// (deactivated) profiles are excluded (p26.63); a batch's profile_id FK still
// resolves to the deactivated row (its audit), it is just no longer offered.
func (q *Queries) ListMappingProfiles(ctx context.Context) ([]MappingProfile, error) {
	rows, err := q.db.QueryContext(ctx, listMappingProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MappingProfile
	for rows.Next() {
		var i MappingProfile
		if err := rows.Scan(&i.ID, &i.Name, &i.Config); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markImportRowDiscarded = `-- name: MarkImportRowDiscarded :exec
UPDATE import_rows
SET status = 'discarded'
WHERE id = ? AND status = 'pending'
`

// p17.3: mark a staged row discarded (status=discarded). The DISCARD REASON is the
// `changes` row's note (DECISIONS p17.1: a discarded row's audit is that change);
// there is no discard_reason column by design. Guarded to status='pending'.
func (q *Queries) MarkImportRowDiscarded(ctx context.Context, id ids.ImportRowID) error {
	_, err := q.db.ExecContext(ctx, markImportRowDiscarded, id)
	return err
}

const markImportRowPosted = `-- name: MarkImportRowPosted :exec
UPDATE import_rows
SET status = 'posted', posted_transaction_id = ?
WHERE id = ? AND status = 'pending'
`

type MarkImportRowPostedParams struct {
	PostedTransactionID sql.NullInt64
	ID                  ids.ImportRowID
}

// p17.3: LINK a staged row to the ledger transaction that posted it (status=posted,
// posted_transaction_id set). Guarded to status='pending' so a double-submit does not
// re-link an already-posted/discarded row (the store also re-reads status first).
func (q *Queries) MarkImportRowPosted(ctx context.Context, arg MarkImportRowPostedParams) error {
	_, err := q.db.ExecContext(ctx, markImportRowPosted, arg.PostedTransactionID, arg.ID)
	return err
}

const pendingOrPostedDedupeHashes = `-- name: PendingOrPostedDedupeHashes :many
SELECT dedupe_hash FROM import_rows
WHERE account_id = ? AND status IN ('pending','posted')
`

// Dedupe LOOKUP source (1): the dedupe_hashes of import rows ALREADY staged
// (pending) or posted on this account -- across ALL batches (a re-upload is a new
// batch), which is what makes cross-batch duplicate flagging work. Discarded rows
// are excluded (a discarded row is not a live duplicate to re-flag against).
func (q *Queries) PendingOrPostedDedupeHashes(ctx context.Context, accountID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, pendingOrPostedDedupeHashes, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var dedupe_hash string
		if err := rows.Scan(&dedupe_hash); err != nil {
			return nil, err
		}
		items = append(items, dedupe_hash)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
