// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: last_used.sql

package sqlc

import (
	"context"
)

const lastHeaderAccountForActor = `-- name: LastHeaderAccountForActor :one
SELECT s.account_id
FROM transactions_versions tv
JOIN changes c ON c.id = tv.change_id
JOIN transactions t ON t.id = tv.entity_id AND t.deleted = 0
JOIN splits s ON s.transaction_id = t.id AND s.position = 0
WHERE tv.op = 'create' AND c.actor_id = ?
ORDER BY c.id DESC
LIMIT 1
`

// The position-0 split account of the transaction MOST RECENTLY CREATED by the given
// actor. "Most recently entered" = the greatest create-change id authored by the actor
// (change id is monotonic insertion order), NOT the transaction's business date -- a
// backdated entry should not win. Only non-deleted transactions count. Joins the live
// splits row (position 0) so the returned account reflects the transaction's current
// header account. Returns no rows when the actor has entered no (non-deleted)
// transaction. Param: the actor's user id.
func (q *Queries) LastHeaderAccountForActor(ctx context.Context, actorID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, lastHeaderAccountForActor, actorID)
	var account_id int64
	err := row.Scan(&account_id)
	return account_id, err
}
