// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Change struct {
	ID      int64
	ActorID int64
	At      string
	Kind    string
	Note    sql.NullString
}

type Currency struct {
	Code     string
	Exponent int64
	Symbol   string
	Name     string
	Active   int64
}

type SubsidiariesVersion struct {
	ID           int64
	EntityID     int64
	ChangeID     int64
	ValidFrom    string
	Op           string
	ParentID     sql.NullInt64
	Name         string
	BaseCurrency string
	Active       int64
	SortOrder    int64
}

type Subsidiary struct {
	ID           int64
	ParentID     sql.NullInt64
	Name         string
	BaseCurrency string
	Active       int64
	SortOrder    int64
}

type User struct {
	ID          int64
	Username    string
	DisplayName string
	CreatedAt   string
	DisabledAt  sql.NullString
}
