// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"

	"cuento/internal/ids"
)

type Account struct {
	ID                ids.AccountID
	ParentID          sql.NullInt64
	Type              string
	DefaultCurrency   string
	FunctionalClass   sql.NullString
	Form990Code       sql.NullString
	Intercompany      int64
	Reconcilable      int64
	Active            int64
	SortOrder         int64
	CreatedAt         string
	DefaultProgramID  sql.NullInt64
	CurrentCash       int64
	ReceivablePayable int64
	Notes             sql.NullString
}

type AccountName struct {
	AccountID ids.AccountID
	Lang      string
	Name      string
}

type AccountNamesVersion struct {
	ID        int64
	EntityID  ids.AccountID
	ChangeID  ids.ChangeID
	ValidFrom string
	Op        string
	Lang      string
	Name      string
}

type AccountSubsidiariesVersion struct {
	ID           int64
	EntityID     ids.AccountID
	ChangeID     ids.ChangeID
	ValidFrom    string
	Op           string
	SubsidiaryID ids.SubsidiaryID
}

type AccountSubsidiary struct {
	AccountID    ids.AccountID
	SubsidiaryID ids.SubsidiaryID
}

type AccountsVersion struct {
	ID                int64
	EntityID          ids.AccountID
	ChangeID          ids.ChangeID
	ValidFrom         string
	Op                string
	ParentID          sql.NullInt64
	Type              string
	DefaultCurrency   string
	FunctionalClass   sql.NullString
	Form990Code       sql.NullString
	Intercompany      int64
	Reconcilable      int64
	Active            int64
	SortOrder         int64
	CreatedAt         string
	DefaultProgramID  sql.NullInt64
	CurrentCash       sql.NullInt64
	ReceivablePayable sql.NullInt64
	Notes             sql.NullString
}

// BudgetPlan is the p27.2 split-derived budget container (a named plan scoped to
// one subsidiary). The p19 schedule/budget-line model was retired in p27.3.
type BudgetPlan struct {
	ID           ids.BudgetPlanID
	Name         string
	SubsidiaryID ids.SubsidiaryID
	Notes        string
}

type BudgetPlansVersion struct {
	ID           int64
	EntityID     ids.BudgetPlanID
	ChangeID     ids.ChangeID
	ValidFrom    string
	Op           string
	Name         string
	SubsidiaryID ids.SubsidiaryID
	Notes        string
}

// BudgetSplit is one projected, dated budget-split (p27.2). Single-legged; the
// balancing cash counter-leg is implicit and unnamed. ProgramID is REQUIRED on
// R/E-categorized legs, FORBIDDEN on A/L legs (store-enforced).
type BudgetSplit struct {
	ID          ids.BudgetSplitID
	PlanID      ids.BudgetPlanID
	Description string
	Date        string
	AccountID   ids.AccountID
	FundID      sql.NullInt64
	ProgramID   sql.NullInt64
	Amount      int64
	Currency    string
}

type BudgetSplitsVersion struct {
	ID          int64
	EntityID    ids.BudgetSplitID
	ChangeID    ids.ChangeID
	ValidFrom   string
	Op          string
	PlanID      ids.BudgetPlanID
	Description string
	Date        string
	AccountID   ids.AccountID
	FundID      sql.NullInt64
	ProgramID   sql.NullInt64
	Amount      int64
	Currency    string
}

type Change struct {
	ID      ids.ChangeID
	ActorID ids.UserID
	At      string
	Kind    string
	Note    sql.NullString
}

type Currency struct {
	Code     string
	Exponent int64
	Symbol   string
	Name     string
	Active   int64
}

type ExchangeRate struct {
	RateDate string
	Base     string
	Quote    string
	Rate     float64
	Source   string
	ChangeID ids.ChangeID
}

type ExpenseReport struct {
	ID                  ids.ExpenseReportID
	SubmitterID         ids.UserID
	SubsidiaryID        ids.SubsidiaryID
	Status              string
	ReviewNotes         string
	PostedTransactionID sql.NullInt64
	CreatedAt           string
	Date                string        // p-golive header: report/txn date ('' = unset -> today at convert)
	Description         string        // p-golive header: prefills the posted txn's main split description
	Memo                string        // p-golive header: prefills the posted txn memo
	Notes               string        // p-golive header: prefills the posted txn notes
	APAccountID         sql.NullInt64 // the main-split payable (defaulted from the sub's default_ap_account_id); NULL = unset
}

type ExpenseReportLine struct {
	ID          ids.ExpenseReportLineID
	ReportID    ids.ExpenseReportID
	AccountID   ids.AccountID
	Amount      int64
	FundID      sql.NullInt64
	ProgramID   sql.NullInt64
	Memo        string
	Description string
}

type ExpenseReportLinesVersion struct {
	ID          int64
	EntityID    ids.ExpenseReportLineID
	ChangeID    ids.ChangeID
	ValidFrom   string
	Op          string
	ReportID    ids.ExpenseReportID
	AccountID   ids.AccountID
	Amount      int64
	FundID      sql.NullInt64
	ProgramID   sql.NullInt64
	Memo        string
	Description string
}

type ExpenseReportsVersion struct {
	ID                  int64
	EntityID            ids.ExpenseReportID
	ChangeID            ids.ChangeID
	ValidFrom           string
	Op                  string
	SubmitterID         ids.UserID
	SubsidiaryID        ids.SubsidiaryID
	Status              string
	ReviewNotes         string
	PostedTransactionID sql.NullInt64
	CreatedAt           string
}

type Form990Line struct {
	Code         string
	Part         string
	Line         string
	Label        string
	AccountTypes string
	Sort         int64
}

type Fund struct {
	ID          ids.FundID
	Name        string
	Funder      string
	Purpose     string
	Restriction string
	ProgramID   sql.NullInt64
	StartDate   sql.NullString
	EndDate     sql.NullString
	Notes       string
	Active      int64
}

type FundSubsidiariesVersion struct {
	ID           int64
	EntityID     ids.FundID
	ChangeID     ids.ChangeID
	ValidFrom    string
	Op           string
	SubsidiaryID ids.SubsidiaryID
}

type FundSubsidiary struct {
	FundID       ids.FundID
	SubsidiaryID ids.SubsidiaryID
}

type FundsVersion struct {
	ID          int64
	EntityID    ids.FundID
	ChangeID    ids.ChangeID
	ValidFrom   string
	Op          string
	Name        string
	Funder      string
	Purpose     string
	Restriction string
	ProgramID   sql.NullInt64
	StartDate   sql.NullString
	EndDate     sql.NullString
	Notes       string
	Active      int64
}

type ImportBatch struct {
	ID           ids.ImportBatchID
	Filename     string
	AccountID    ids.AccountID
	SubsidiaryID ids.SubsidiaryID
	ProfileID    ids.MappingProfileID
	UploadedBy   ids.UserID
	UploadedAt   string
}

type ImportRow struct {
	ID                  ids.ImportRowID
	BatchID             ids.ImportBatchID
	AccountID           ids.AccountID
	RawJson             string
	ParsedDate          sql.NullString
	ParsedAmount        sql.NullInt64
	ParsedPayee         sql.NullString
	ParsedMemo          sql.NullString
	Status              string
	DedupeHash          string
	PostedTransactionID sql.NullInt64
}

type MappingProfile struct {
	ID     ids.MappingProfileID
	Name   string
	Config string
}

type OrgSetting struct {
	Key   string
	Value string
}

type Program struct {
	ID        ids.ProgramID
	ParentID  sql.NullInt64
	Name      string
	Active    int64
	SortOrder int64
}

type ProgramsVersion struct {
	ID        int64
	EntityID  ids.ProgramID
	ChangeID  ids.ChangeID
	ValidFrom string
	Op        string
	ParentID  sql.NullInt64
	Name      string
	Active    int64
	SortOrder int64
}

type Reconciliation struct {
	ID               ids.ReconciliationID
	AccountID        ids.AccountID
	StatementDate    string
	StatementBalance int64
	Currency         string
	Status           string
	Notes            string
}

type ReconciliationsVersion struct {
	ID               int64
	EntityID         ids.ReconciliationID
	ChangeID         ids.ChangeID
	ValidFrom        string
	Op               string
	AccountID        ids.AccountID
	StatementDate    string
	StatementBalance int64
	Currency         string
	Status           string
	Notes            string
}

type ReportGroup struct {
	Name string
	Sort int64
}

type Session struct {
	Token  string
	Data   []byte
	Expiry float64
}

type Split struct {
	ID               ids.SplitID
	TransactionID    ids.TransactionID
	AccountID        ids.AccountID
	Amount           int64
	FundID           sql.NullInt64
	ProgramID        sql.NullInt64
	FunctionalClass  sql.NullString
	Memo             string
	Position         int64
	ReconciliationID sql.NullInt64
	Description      string
}

type SplitsVersion struct {
	ID              int64
	EntityID        ids.SplitID
	ChangeID        ids.ChangeID
	ValidFrom       string
	Op              string
	TransactionID   ids.TransactionID
	AccountID       ids.AccountID
	Amount          int64
	FundID          sql.NullInt64
	ProgramID       sql.NullInt64
	FunctionalClass sql.NullString
	Memo            string
	Position        int64
	Description     string
}

type SubsidiariesVersion struct {
	ID           int64
	EntityID     ids.SubsidiaryID
	ChangeID     ids.ChangeID
	ValidFrom    string
	Op           string
	ParentID     sql.NullInt64
	Name         string
	BaseCurrency string
	Active       int64
	SortOrder    int64
}

type Subsidiary struct {
	ID                 ids.SubsidiaryID
	ParentID           sql.NullInt64
	Name               string
	BaseCurrency       string
	Active             int64
	SortOrder          int64
	DefaultApAccountID sql.NullInt64
}

type Transaction struct {
	ID           ids.TransactionID
	Date         string
	SubsidiaryID ids.SubsidiaryID
	Memo         string
	Currency     string
	Deleted      int64
	Notes        string
}

type TransactionsVersion struct {
	ID           int64
	EntityID     ids.TransactionID
	ChangeID     ids.ChangeID
	ValidFrom    string
	Op           string
	Date         string
	SubsidiaryID ids.SubsidiaryID
	Memo         string
	Currency     string
	Deleted      int64
	Notes        string
}

type User struct {
	ID                  ids.UserID
	Username            string
	DisplayName         string
	CreatedAt           string
	DisabledAt          sql.NullString
	PasswordHash        sql.NullString
	IsAdmin             int64
	TxnPerm             string
	Locale              string
	DateFormat          string
	NumberFormat        string
	DisplayMode         string
	NegStyle            string
	Theme               string
	DefaultSubsidiaryID sql.NullInt64
	CanSubmitExpenses   int64
	DefaultProgramID    sql.NullInt64
}

type UserReportGrant struct {
	UserID    ids.UserID
	GroupName string
	ProgramID sql.NullInt64
}

type UserReportGrantsVersion struct {
	ID        int64
	EntityID  ids.UserID
	ChangeID  ids.ChangeID
	ValidFrom string
	Op        string
	GroupName string
	ProgramID sql.NullInt64
}

type UsersVersion struct {
	ID                  int64
	EntityID            ids.UserID
	ChangeID            ids.ChangeID
	ValidFrom           string
	Op                  string
	Username            string
	DisplayName         string
	CreatedAt           string
	DisabledAt          sql.NullString
	IsAdmin             int64
	TxnPerm             string
	Locale              string
	DateFormat          string
	NumberFormat        string
	DisplayMode         string
	NegStyle            string
	Theme               string
	DefaultSubsidiaryID sql.NullInt64
	CanSubmitExpenses   int64
	DefaultProgramID    sql.NullInt64
}
