// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: org_settings.sql

package sqlc

import (
	"context"
)

const getOrgSetting = `-- name: GetOrgSetting :one

SELECT value FROM org_settings WHERE key = ?
`

// org_settings is static CONFIG reference data (p11.4): a plain key/value table,
// NOT a versioned business table, so these are plain reads and an idempotent
// upsert -- OUTSIDE the write funnel, like currencies/report_groups (rule 2 permits
// reads and config upserts via sqlc). ASCII only (p04.2 sqlc quirk).
// The value for one config key. sql.ErrNoRows when the key is unset; the store
// turns that into a caller-supplied default.
func (q *Queries) GetOrgSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getOrgSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const listOrgSettings = `-- name: ListOrgSettings :many
SELECT key, value FROM org_settings ORDER BY key
`

// Every config key/value, ordered by key for deterministic output.
func (q *Queries) ListOrgSettings(ctx context.Context) ([]OrgSetting, error) {
	rows, err := q.db.QueryContext(ctx, listOrgSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgSetting
	for rows.Next() {
		var i OrgSetting
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOrgSetting = `-- name: UpsertOrgSetting :exec
INSERT INTO org_settings (key, value)
VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type UpsertOrgSettingParams struct {
	Key   string
	Value string
}

// Idempotent insert-or-update of one config key. Admin writes are configuration,
// not audited business mutations, so there is no changes/version wiring.
func (q *Queries) UpsertOrgSetting(ctx context.Context, arg UpsertOrgSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertOrgSetting, arg.Key, arg.Value)
	return err
}
