// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: programs.sql

package sqlc

import (
	"context"
	"database/sql"

	"cuento/internal/ids"
)

const countActiveProgramChildren = `-- name: CountActiveProgramChildren :one
SELECT COUNT(*) FROM programs
WHERE parent_id = ? AND active = 1
`

// Active children of a program. DeactivateProgram is blocked while > 0
// (ErrProgramHasActiveChildren): deactivating a parent with live descendants
// would orphan active programs behind an inactive one.
func (q *Queries) CountActiveProgramChildren(ctx context.Context, parentID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveProgramChildren, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProgram = `-- name: GetProgram :one
SELECT id, parent_id, name, active, sort_order
FROM programs
WHERE id = ?
`

func (q *Queries) GetProgram(ctx context.Context, id ids.ProgramID) (Program, error) {
	row := q.db.QueryRowContext(ctx, getProgram, id)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Active,
		&i.SortOrder,
	)
	return i, err
}

const insertProgram = `-- name: InsertProgram :one

INSERT INTO programs (parent_id, name, active, sort_order)
VALUES (?, ?, ?, ?)
RETURNING id
`

type InsertProgramParams struct {
	ParentID  sql.NullInt64
	Name      string
	Active    int64
	SortOrder int64
}

// p07.1: program operations. All SQL for the store's program methods lives here
// (rule 6). This copies the version-append convention established in
// subsidiaries.sql (p04.2) MINUS base_currency: the entity op does the live write
// inside the funnel's fn, then appends a snapshot-from-live version row via
// InsertProgramVersion, so the version row is byte-identical to the live row (Z3
// can never diverge) and valid_from == changes.at BY CONSTRUCTION.
//
// Query names are DISTINCT from the subsidiary ones (InsertProgram vs
// InsertSubsidiary, ProgramTree vs SubTree, ProgramDescendants vs Descendants,
// CountActiveProgramChildren vs CountActiveChildren): sqlc emits into one package,
// so a name collision would fail generation.
//
// NOTE: keep every comment and identifier in this file PURE ASCII. sqlc v1.31.1
// miscounts byte offsets when a query file contains multi-byte UTF-8, corrupting
// the generated SQL for the WHOLE file (see docs/DECISIONS.md p04.2).
// Live insert of a CHILD. parent_id is validated present/valid in the store
// (ErrProgramSecondRoot / ErrProgramParentMissing) BEFORE this runs, so a second
// root never reaches the trigger. Returns the new id for the store to snapshot.
func (q *Queries) InsertProgram(ctx context.Context, arg InsertProgramParams) (ids.ProgramID, error) {
	row := q.db.QueryRowContext(ctx, insertProgram,
		arg.ParentID,
		arg.Name,
		arg.Active,
		arg.SortOrder,
	)
	var id ids.ProgramID
	err := row.Scan(&id)
	return id, err
}

const insertProgramVersion = `-- name: InsertProgramVersion :exec
INSERT INTO programs_versions
  (entity_id, change_id, valid_from, op, parent_id, name, active, sort_order)
SELECT p.id, c.id, c.at, ?, p.parent_id, p.name, p.active, p.sort_order
FROM programs p, changes c
WHERE c.id = ? AND p.id = ?
`

type InsertProgramVersionParams struct {
	Op   string
	ID   ids.ChangeID
	ID_2 ids.ProgramID
}

// The snapshot-from-live version append (rule 5, D4). Reads the CURRENT live row
// (so it must run AFTER the live write) and copies every business column, so the
// version row is byte-identical to the live row; valid_from is taken from the
// change's own `at`, so valid_from == changes.at BY CONSTRUCTION. Snapshot column
// set matches 00008_programs.sql exactly.
//
// Params are PLAIN POSITIONAL (?), each used once: op, then change_id (bound in
// the WHERE, its id + at selected into the row), then entity_id. The generated
// struct fields are Op, ID (change_id = c.id), ID_2 (entity_id = p.id); the store
// wraps that behind one insertProgramVersion helper.
func (q *Queries) InsertProgramVersion(ctx context.Context, arg InsertProgramVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertProgramVersion, arg.Op, arg.ID, arg.ID_2)
	return err
}

const programDescendants = `-- name: ProgramDescendants :many
WITH RECURSIVE prog(id, parent_id, name, active, sort_order) AS (
  SELECT p.id, p.parent_id, p.name, p.active, p.sort_order
  FROM programs p
  WHERE p.id = ?
  UNION ALL
  SELECT p.id, p.parent_id, p.name, p.active, p.sort_order
  FROM programs p
  JOIN prog ON p.parent_id = prog.id
)
SELECT prog.id, prog.parent_id, prog.name, prog.active, prog.sort_order
FROM prog
`

type ProgramDescendantsRow struct {
	ID        ids.ProgramID
	ParentID  sql.NullInt64
	Name      string
	Active    int64
	SortOrder int64
}

// Self + transitive closure of a program (the primitive report scoping and the
// move cycle check use, D24). Self is the recursive base case, so it is ALWAYS
// included; the store's cycle check (new parent must not be self nor any
// descendant) relies on that.
func (q *Queries) ProgramDescendants(ctx context.Context, id ids.ProgramID) ([]ProgramDescendantsRow, error) {
	rows, err := q.db.QueryContext(ctx, programDescendants, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProgramDescendantsRow
	for rows.Next() {
		var i ProgramDescendantsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Active,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const programTree = `-- name: ProgramTree :many
WITH RECURSIVE tree(id, parent_id, name, active, sort_order, path) AS (
  SELECT p.id, p.parent_id, p.name, p.active, p.sort_order,
         printf('%020d.%020d', p.sort_order, p.id)
  FROM programs p
  WHERE p.parent_id IS NULL
  UNION ALL
  SELECT p.id, p.parent_id, p.name, p.active, p.sort_order,
         t.path || '/' || printf('%020d.%020d', p.sort_order, p.id)
  FROM programs p
  JOIN tree t ON p.parent_id = t.id
)
SELECT tree.id, tree.parent_id, tree.name, tree.active, tree.sort_order
FROM tree
ORDER BY tree.path
`

type ProgramTreeRow struct {
	ID        ids.ProgramID
	ParentID  sql.NullInt64
	Name      string
	Active    int64
	SortOrder int64
}

// All programs in DEPTH-FIRST (pre-order) order. A materialized path of
// zero-padded (sort_order, id) pairs per level makes ORDER BY path a true
// pre-order traversal; children are ordered by sort_order then id.
func (q *Queries) ProgramTree(ctx context.Context) ([]ProgramTreeRow, error) {
	rows, err := q.db.QueryContext(ctx, programTree)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProgramTreeRow
	for rows.Next() {
		var i ProgramTreeRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Active,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProgram = `-- name: UpdateProgram :exec
UPDATE programs
SET parent_id = ?, name = ?, active = ?, sort_order = ?
WHERE id = ?
`

type UpdateProgramParams struct {
	ParentID  sql.NullInt64
	Name      string
	Active    int64
	SortOrder int64
	ID        ids.ProgramID
}

// Live update: rename / move (parent) / active / sort. The store reads the
// current row (GetProgram), overrides the caller's fields, and writes the full
// desired state here, keeping snapshot-from-live trivial.
func (q *Queries) UpdateProgram(ctx context.Context, arg UpdateProgramParams) error {
	_, err := q.db.ExecContext(ctx, updateProgram,
		arg.ParentID,
		arg.Name,
		arg.Active,
		arg.SortOrder,
		arg.ID,
	)
	return err
}

const countSplitsForProgram = `-- name: CountSplitsForProgram :one
SELECT COUNT(*) FROM splits WHERE program_id = ?
`

// How many splits currently carry this program_id (p11.5b). The merge preview
// reports it as the number of transaction lines that will move to the destination,
// reusing the SAME predicate MergeProgram repoints from so the preview never lies.
func (q *Queries) CountSplitsForProgram(ctx context.Context, programID ids.ProgramID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSplitsForProgram, sql.NullInt64{Int64: int64(programID), Valid: true})
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFundScopeBlockingSplits = `-- name: CountFundScopeBlockingSplits :one
SELECT COUNT(*)
FROM splits s
JOIN funds f ON f.id = s.fund_id
WHERE s.program_id = ?1
  AND f.program_id IS NOT NULL
  AND ?2 NOT IN (
    WITH RECURSIVE sub(id) AS (
      SELECT f.program_id
      UNION ALL
      SELECT p.id FROM programs p JOIN sub ON p.parent_id = sub.id
    )
    SELECT id FROM sub)
`

type CountFundScopeBlockingSplitsParams struct {
	Src ids.ProgramID
	Dst ids.ProgramID
}

// How many splits on the SOURCE program (program_id = src) would leave their fund's
// program scope if repointed to the DESTINATION (p11.5b Z15b block-guard). A split
// tagged a FUND whose program scope R is set must carry a program inside R's subtree
// (D20, Z15b; the same rule PostTransaction enforces as ErrFundProgramScope). Merging
// src into dst repoints the split's program to dst, so the merge is REFUSED when any
// such split's fund program scope R does NOT contain dst -- otherwise the repoint would
// write a Z15b hole (nothing at the trigger layer guards the fund-subtree scope). Full
// fund-scope repointing is out of scope (mirrors the account merge's recon backlog).
// Params: src (the source program), dst (the candidate destination).
func (q *Queries) CountFundScopeBlockingSplits(ctx context.Context, arg CountFundScopeBlockingSplitsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFundScopeBlockingSplits,
		sql.NullInt64{Int64: int64(arg.Src), Valid: true},
		int64(arg.Dst),
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const splitIdsByProgram = `-- name: SplitIdsByProgram :many
SELECT id FROM splits WHERE program_id = ? ORDER BY id
`

// All split ids currently on a program, oldest first. Used by MergeProgram to
// repoint each split's program_id individually and version it (snapshot-from-live),
// exactly as SplitIdsByAccount does for the account merge. NOT filtered by
// transaction.deleted: a merge clears the source program entirely so its history
// reads coherently. Captured BEFORE any repoint write so the moved rows are not
// confused with the destination's pre-existing splits.
func (q *Queries) SplitIdsByProgram(ctx context.Context, programID ids.ProgramID) ([]ids.SplitID, error) {
	rows, err := q.db.QueryContext(ctx, splitIdsByProgram, sql.NullInt64{Int64: int64(programID), Valid: true})
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ids.SplitID
	for rows.Next() {
		var id ids.SplitID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repointSplitProgram = `-- name: RepointSplitProgram :exec
UPDATE splits SET program_id = ? WHERE id = ?
`

type RepointSplitProgramParams struct {
	ProgramID ids.ProgramID
	ID        ids.SplitID
}

// Move ONE split to a new program_id (the merge repoint). The store versions the
// split op='update' AFTER this so the snapshot-from-live row records program_id =
// the destination. id last.
func (q *Queries) RepointSplitProgram(ctx context.Context, arg RepointSplitProgramParams) error {
	_, err := q.db.ExecContext(ctx, repointSplitProgram, arg.ProgramID, arg.ID)
	return err
}

const programChildIDs = `-- name: ProgramChildIDs :many
SELECT id FROM programs WHERE parent_id = ? ORDER BY id
`

// The ids of the DIRECT children of a program (parent_id = ?), oldest first. Used
// by MergeProgram to reparent each child onto the destination and version it. The
// store guards dst against being src or a descendant of src (ErrCycle) BEFORE this,
// so reparenting the children under dst can never form a cycle.
func (q *Queries) ProgramChildIDs(ctx context.Context, parentID ids.ProgramID) ([]ids.ProgramID, error) {
	rows, err := q.db.QueryContext(ctx, programChildIDs, sql.NullInt64{Int64: int64(parentID), Valid: true})
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ids.ProgramID
	for rows.Next() {
		var id ids.ProgramID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repointProgramParent = `-- name: RepointProgramParent :exec
UPDATE programs SET parent_id = ? WHERE id = ?
`

type RepointProgramParentParams struct {
	ParentID ids.ProgramID
	ID       ids.ProgramID
}

// Reparent ONE program to a new parent_id (the merge child-repoint). The store
// versions the program op='update' AFTER this. id last.
func (q *Queries) RepointProgramParent(ctx context.Context, arg RepointProgramParentParams) error {
	_, err := q.db.ExecContext(ctx, repointProgramParent, sql.NullInt64{Int64: int64(arg.ParentID), Valid: true}, arg.ID)
	return err
}

const reportGrantsByProgram = `-- name: ReportGrantsByProgram :many
SELECT user_id, group_name FROM user_report_grants
WHERE program_id = ? ORDER BY user_id, group_name
`

type ReportGrantsByProgramRow struct {
	UserID    ids.UserID
	GroupName string
}

// Every (user_id, group_name) grant currently scoped to a program (program_id = ?).
// MergeProgram re-scopes each to the destination; the scope is a mutable ATTRIBUTE
// (not part of the (user, group) key), so a re-scope is a delete+create version
// pair (no 'update' op). Two grants for the same (user, group) can never both exist
// (the PK forbids it), so repointing program_id never collides.
func (q *Queries) ReportGrantsByProgram(ctx context.Context, programID ids.ProgramID) ([]ReportGrantsByProgramRow, error) {
	rows, err := q.db.QueryContext(ctx, reportGrantsByProgram, sql.NullInt64{Int64: int64(programID), Valid: true})
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportGrantsByProgramRow
	for rows.Next() {
		var i ReportGrantsByProgramRow
		if err := rows.Scan(&i.UserID, &i.GroupName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repointReportGrantProgram = `-- name: RepointReportGrantProgram :exec
UPDATE user_report_grants SET program_id = ? WHERE user_id = ? AND group_name = ?
`

type RepointReportGrantProgramParams struct {
	ProgramID ids.ProgramID
	UserID    ids.UserID
	GroupName string
}

// Move ONE grant's program scope to a new program_id (the merge re-scope). The
// store snapshots op='delete' BEFORE this and op='create' AFTER (a scope change is
// delete+create, no 'update' op). Keyed on (user_id, group_name); program_id first.
func (q *Queries) RepointReportGrantProgram(ctx context.Context, arg RepointReportGrantProgramParams) error {
	_, err := q.db.ExecContext(ctx, repointReportGrantProgram, sql.NullInt64{Int64: int64(arg.ProgramID), Valid: true}, arg.UserID, arg.GroupName)
	return err
}
