// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rates.sql

package sqlc

import (
	"context"

	"cuento/internal/ids"
)

const insertRate = `-- name: InsertRate :exec

INSERT INTO exchange_rates (rate_date, base, quote, rate, source, change_id)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(rate_date, base, quote) DO UPDATE SET
  rate = excluded.rate, source = excluded.source, change_id = excluded.change_id
`

type InsertRateParams struct {
	RateDate string
	Base     string
	Quote    string
	Rate     float64
	Source   string
	ChangeID ids.ChangeID
}

// exchange_rates queries (p14.1). ASCII only, POSITIONAL ? params (p04.2 sqlc
// quirk). exchange_rates is change-id-anchored reference data (NOT versioned): the
// INSERT carries the funnel's changeID directly, there is no snapshot-from-live
// version append, so no INSERT...SELECT and no numbered-param concern.
// One rate row. Called in a loop by PutRates, once per pair in a batch, all under
// ONE change_id (the funnel binds the batch to a single changes row). ON CONFLICT
// makes a re-load of an existing (date, base, quote) idempotent -- it refreshes
// the rate/source and re-anchors change_id to the loading batch (a ratesync retry
// or a manual correction over the same day/pair overwrites cleanly rather than
// PK-colliding).
func (q *Queries) InsertRate(ctx context.Context, arg InsertRateParams) error {
	_, err := q.db.ExecContext(ctx, insertRate,
		arg.RateDate,
		arg.Base,
		arg.Quote,
		arg.Rate,
		arg.Source,
		arg.ChangeID,
	)
	return err
}

const rateOnOrBefore = `-- name: RateOnOrBefore :one
SELECT rate_date, rate
FROM exchange_rates
WHERE base = ? AND quote = ? AND rate_date <= ?
ORDER BY rate_date DESC
LIMIT 1
`

type RateOnOrBeforeParams struct {
	Base     string
	Quote    string
	RateDate string
}

type RateOnOrBeforeRow struct {
	RateDate string
	Rate     float64
}

// The rate for base->quote effective ON OR BEFORE the given date: the row with the
// greatest rate_date <= the target. Returns rate AND its ACTUAL rate_date so a
// report can footnote staleness ("as of <rate_date>"). sql.ErrNoRows when no row
// for the pair is on-or-before the date; the store turns that into the reciprocal
// fallback or ErrRateMissing.
func (q *Queries) RateOnOrBefore(ctx context.Context, arg RateOnOrBeforeParams) (RateOnOrBeforeRow, error) {
	row := q.db.QueryRowContext(ctx, rateOnOrBefore, arg.Base, arg.Quote, arg.RateDate)
	var i RateOnOrBeforeRow
	err := row.Scan(&i.RateDate, &i.Rate)
	return i, err
}
