// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconciliations.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countOpenReconciliations = `-- name: CountOpenReconciliations :one
SELECT COUNT(*) FROM reconciliations
WHERE account_id = ? AND currency = ? AND status = 'open'
`

type CountOpenReconciliationsParams struct {
	AccountID int64
	Currency  string
}

// How many OPEN reconciliations already exist for an (account, currency). The
// store rejects a second concurrent open recon on the same pair (one open recon
// per (account, currency), D13) BEFORE inserting.
func (q *Queries) CountOpenReconciliations(ctx context.Context, arg CountOpenReconciliationsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenReconciliations, arg.AccountID, arg.Currency)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finalizedReconciledSplitIDs = `-- name: FinalizedReconciledSplitIDs :many
SELECT s.id
FROM splits s
JOIN reconciliations r ON r.id = s.reconciliation_id
WHERE s.transaction_id = ? AND r.status = 'finalized'
`

// The ids of splits on a given transaction that are cleared against a FINALIZED
// reconciliation. UpdateTransaction uses this to reject financial edits (amount/
// account/fund on a changed split, split deletion, header date/currency change)
// BEFORE the split-lock trigger fires -- a clean typed error instead of a raw
// ABORT. NULL reconciliation_id (uncleared) and open-recon splits are excluded.
func (q *Queries) FinalizedReconciledSplitIDs(ctx context.Context, transactionID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, finalizedReconciledSplitIDs, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finalizedReconciliationsForAccount = `-- name: FinalizedReconciliationsForAccount :many
SELECT r.id, r.statement_date, r.statement_balance, r.currency,
       CAST((SELECT MAX(v.valid_from) FROM reconciliations_versions v
        WHERE v.entity_id = r.id AND v.op = 'update' AND v.status = 'finalized') AS TEXT) AS finalized_at
FROM reconciliations r
WHERE r.account_id = ? AND r.status = 'finalized'
ORDER BY r.statement_date DESC, r.id DESC
`

type FinalizedReconciliationsForAccountRow struct {
	ID               int64
	StatementDate    string
	StatementBalance int64
	Currency         string
	FinalizedAt      string
}

// The p16.4 HISTORY source: every FINALIZED reconciliation on an account (both
// currencies), newest statement first -- the audit trail of completed reconciliations.
// finalized_at is the valid_from of the reconciliations_versions row that recorded the
// finalize (the op='update' snapshot whose status is 'finalized'); MAX picks the most
// recent finalize event when a recon was reopened + refinalized. There is no
// finalized_at column on reconciliations (00014), so the version twin is the only
// audit source for WHEN a statement was finalized. Ordered so the history reads
// newest-first. Param: account_id.
func (q *Queries) FinalizedReconciliationsForAccount(ctx context.Context, accountID int64) ([]FinalizedReconciliationsForAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, finalizedReconciliationsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinalizedReconciliationsForAccountRow
	for rows.Next() {
		var i FinalizedReconciliationsForAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.StatementDate,
			&i.StatementBalance,
			&i.Currency,
			&i.FinalizedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReconciliation = `-- name: GetReconciliation :one
SELECT id, account_id, statement_date, statement_balance, currency, status, notes
FROM reconciliations
WHERE id = ?
`

func (q *Queries) GetReconciliation(ctx context.Context, id int64) (Reconciliation, error) {
	row := q.db.QueryRowContext(ctx, getReconciliation, id)
	var i Reconciliation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.StatementDate,
		&i.StatementBalance,
		&i.Currency,
		&i.Status,
		&i.Notes,
	)
	return i, err
}

const getSplitForReconcile = `-- name: GetSplitForReconcile :one
SELECT s.id, s.account_id, s.reconciliation_id, s.transaction_id,
       t.currency, t.deleted
FROM splits s
JOIN transactions t ON t.id = s.transaction_id
WHERE s.id = ?
`

type GetSplitForReconcileRow struct {
	ID               int64
	AccountID        int64
	ReconciliationID sql.NullInt64
	TransactionID    int64
	Currency         string
	Deleted          int64
}

// One split plus its transaction's currency and deleted flag -- what
// SetSplitReconciled validates against (split account == recon account, split
// currency (from its txn, D3) == recon currency). transaction_id is returned so a
// caller can locate the parent txn.
func (q *Queries) GetSplitForReconcile(ctx context.Context, id int64) (GetSplitForReconcileRow, error) {
	row := q.db.QueryRowContext(ctx, getSplitForReconcile, id)
	var i GetSplitForReconcileRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ReconciliationID,
		&i.TransactionID,
		&i.Currency,
		&i.Deleted,
	)
	return i, err
}

const hasLaterFinalizedReconciliation = `-- name: HasLaterFinalizedReconciliation :one
SELECT EXISTS (
  SELECT 1 FROM reconciliations l
  WHERE l.status = 'finalized' AND l.account_id = ?
    AND l.currency = ?
    AND (l.statement_date > ?
         OR (l.statement_date = ? AND l.id > ?))
) AS has_later
`

type HasLaterFinalizedReconciliationParams struct {
	AccountID       int64
	Currency        string
	StatementDate   string
	StatementDate_2 string
	ID              int64
}

// 1 when a LATER FINALIZED reconciliation exists for the SAME (account, currency),
// by (statement_date, id) order, strictly AFTER this one. Reopen uses it to enforce
// reverse-chronological reopen (p16.5, Gap 2): reopening an earlier statement while
// a later finalized one exists would corrupt the opening chain. The mirror image of
// PriorFinalizedStatementBalance's "prior" bound. Params: account_id, currency,
// statement_date, statement_date, id (of the recon being reopened).
func (q *Queries) HasLaterFinalizedReconciliation(ctx context.Context, arg HasLaterFinalizedReconciliationParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasLaterFinalizedReconciliation,
		arg.AccountID,
		arg.Currency,
		arg.StatementDate,
		arg.StatementDate_2,
		arg.ID,
	)
	var has_later bool
	err := row.Scan(&has_later)
	return has_later, err
}

const insertReconciliation = `-- name: InsertReconciliation :one

INSERT INTO reconciliations (account_id, statement_date, statement_balance, currency)
VALUES (?, ?, ?, ?)
RETURNING id
`

type InsertReconciliationParams struct {
	AccountID        int64
	StatementDate    string
	StatementBalance int64
	Currency         string
}

// p16.2: reconciliation-lifecycle SQL (D13/D20). All SQL for the store's
// reconciliation methods lives here (rule 6). This copies the version-append
// convention subsidiaries.sql (p04.2) / funds.sql (p07.3) established: the entity
// op does the live write inside the funnel's fn, then appends a snapshot-from-live
// version row, so each version row is byte-identical to its live row (Z3 can never
// diverge) and valid_from == changes.at BY CONSTRUCTION.
//
// A reconciliation is LIVE-ONLY on splits (splits.reconciliation_id is NOT
// versioned, 00014), so clearing/unclearing a split UPDATES that one column and
// mints NO split version -- the audited reconciliation event is finalization,
// recorded on reconciliations (+ its versions twin). SetSplitReconciled still runs
// through the funnel (rule 2): a changes row IS emitted for the tx boundary/actor;
// only the split-VERSION append is skipped (00014's live-only decision).
//
// Finalize's zero-difference gate MIRRORS ledger Z9 (checks.go sqlZ9) exactly --
// same opening lookup (prior FINALIZED recon, same account+currency, ordered
// statement_date DESC then id DESC, COALESCE 0) and same cleared-sum (SUM(amount)
// of splits joined to NON-DELETED transactions). Keeping them byte-identical is the
// tie: if Finalize succeeds, Z9 passes on that finalized recon.
//
// NOTE: keep every comment and identifier in this file PURE ASCII. sqlc v1.31.1
// miscounts byte offsets when a query file contains multi-byte UTF-8, corrupting
// the generated SQL for the WHOLE file (see docs/DECISIONS.md p04.2).
// Live insert of an OPEN reconciliation (status defaults 'open', notes ”). Per
// (account, currency) across all funds (D13). Returns the new id for the store to
// snapshot + return.
func (q *Queries) InsertReconciliation(ctx context.Context, arg InsertReconciliationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertReconciliation,
		arg.AccountID,
		arg.StatementDate,
		arg.StatementBalance,
		arg.Currency,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertReconciliationVersion = `-- name: InsertReconciliationVersion :exec
INSERT INTO reconciliations_versions
  (entity_id, change_id, valid_from, op, account_id, statement_date,
   statement_balance, currency, status, notes)
SELECT r.id, c.id, c.at, ?, r.account_id, r.statement_date,
       r.statement_balance, r.currency, r.status, r.notes
FROM reconciliations r, changes c
WHERE c.id = ? AND r.id = ?
`

type InsertReconciliationVersionParams struct {
	Op   string
	ID   int64
	ID_2 int64
}

// Snapshot-from-live version append for reconciliations (STANDARD single-column
// entity, entity_id = reconciliations.id). Reads the CURRENT live row (so it MUST
// run AFTER the live write) and copies every business column, so the version row is
// byte-identical to the live row; valid_from is taken from the change's own `at`.
// Snapshot column set matches 00014_reconciliations.sql exactly. Params (plain
// positional, each used once): op, change_id, entity_id -> generated fields Op,
// ID (change_id), ID_2 (entity_id).
func (q *Queries) InsertReconciliationVersion(ctx context.Context, arg InsertReconciliationVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertReconciliationVersion, arg.Op, arg.ID, arg.ID_2)
	return err
}

const listReconcilableAccounts = `-- name: ListReconcilableAccounts :many
SELECT id, default_currency
FROM accounts
WHERE reconcilable = 1 AND active = 1
ORDER BY sort_order, id
`

type ListReconcilableAccountsRow struct {
	ID              int64
	DefaultCurrency string
}

// The p16.3 recon LIST source: every ACTIVE account flagged reconcilable (D13). A
// reconciliation may only start on such an account (StartReconciliation rejects the
// rest). default_currency is the statement-currency prefill (a bank account is
// single-currency); the account's resolved name comes from the store's name
// lookup, so only id + default_currency are needed here. Ordered for a stable list.
func (q *Queries) ListReconcilableAccounts(ctx context.Context) ([]ListReconcilableAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReconcilableAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReconcilableAccountsRow
	for rows.Next() {
		var i ListReconcilableAccountsRow
		if err := rows.Scan(&i.ID, &i.DefaultCurrency); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationsForAccount = `-- name: ListReconciliationsForAccount :many
SELECT id, account_id, statement_date, statement_balance, currency, status, notes
FROM reconciliations
WHERE account_id = ?
ORDER BY statement_date DESC, id DESC
`

// Every reconciliation on an account (both currencies, open + finalized), newest
// statement first. The recon LIST uses this to show, per reconcilable account, the
// last finalized statement (date + balance) for the opening prefill and any OPEN
// recon to link straight to its workspace. Ordered so the caller can pick the
// latest finalized / open per currency without a second query.
func (q *Queries) ListReconciliationsForAccount(ctx context.Context, accountID int64) ([]Reconciliation, error) {
	rows, err := q.db.QueryContext(ctx, listReconciliationsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reconciliation
	for rows.Next() {
		var i Reconciliation
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.StatementDate,
			&i.StatementBalance,
			&i.Currency,
			&i.Status,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const priorFinalizedStatementBalance = `-- name: PriorFinalizedStatementBalance :one
SELECT CAST(COALESCE((
  SELECT p.statement_balance FROM reconciliations p
  WHERE p.status = 'finalized' AND p.account_id = ?
    AND p.currency = ?
    AND (p.statement_date < ?
         OR (p.statement_date = ? AND p.id < ?))
  ORDER BY p.statement_date DESC, p.id DESC LIMIT 1
), 0) AS INTEGER)
`

type PriorFinalizedStatementBalanceParams struct {
	AccountID       int64
	Currency        string
	StatementDate   string
	StatementDate_2 string
	ID              int64
}

// The opening balance for a reconciliation: the statement_balance of the prior
// FINALIZED recon for the SAME (account, currency), by (statement_date, id) order,
// strictly before this one. COALESCE 0 when this is the first. Byte-identical to
// Z9's opening subquery. Params: account_id, currency, statement_date, id (the
// statement_date and id of the recon being finalized, to bound "prior").
func (q *Queries) PriorFinalizedStatementBalance(ctx context.Context, arg PriorFinalizedStatementBalanceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, priorFinalizedStatementBalance,
		arg.AccountID,
		arg.Currency,
		arg.StatementDate,
		arg.StatementDate_2,
		arg.ID,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const reconciliationClearedSplits = `-- name: ReconciliationClearedSplits :many
SELECT s.id, s.transaction_id, s.amount, s.fund_id, s.memo, s.description,
       t.date, t.subsidiary_id, t.memo AS txn_memo
FROM splits s
JOIN transactions t ON t.id = s.transaction_id
WHERE s.reconciliation_id = ?
  AND t.deleted = 0
ORDER BY t.date, s.id
`

type ReconciliationClearedSplitsRow struct {
	ID            int64
	TransactionID int64
	Amount        int64
	FundID        sql.NullInt64
	Memo          string
	Description   string
	Date          string
	SubsidiaryID  int64
	TxnMemo       string
}

// The p16.4 statement report's INCLUDED (cleared) splits for ONE reconciliation:
// every split cleared against reconciliation_id on a NON-DELETED transaction. The
// predicate matches ReconciliationClearedSum EXACTLY (reconciliation_id = ? AND
// t.deleted = 0), so the golden identity holds: SUM(amount) over these rows equals
// the recon's cleared total, hence opening + Sigma(these) == statement_balance. The
// row shape mirrors WorkspaceSplits (date, payee, memo, fund, amount, txn id) so the
// report reuses the register-row rendering. Ordered ascending by (date, split id) so
// the statement reads chronologically. NOTE: no account/currency/scope filter -- a
// reconciliation spans all funds AND all subsidiaries (D13/D20), and its cleared set
// is fully identified by reconciliation_id; scoping would shrink the set and break the
// chain. Param: reconciliation_id.
func (q *Queries) ReconciliationClearedSplits(ctx context.Context, reconciliationID sql.NullInt64) ([]ReconciliationClearedSplitsRow, error) {
	rows, err := q.db.QueryContext(ctx, reconciliationClearedSplits, reconciliationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReconciliationClearedSplitsRow
	for rows.Next() {
		var i ReconciliationClearedSplitsRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.Amount,
			&i.FundID,
			&i.Memo,
			&i.Description,
			&i.Date,
			&i.SubsidiaryID,
			&i.TxnMemo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconciliationClearedSum = `-- name: ReconciliationClearedSum :one
SELECT CAST(COALESCE(SUM(s.amount), 0) AS INTEGER)
FROM splits s
JOIN transactions t ON t.id = s.transaction_id
WHERE s.reconciliation_id = CAST(? AS INTEGER) AND t.deleted = 0
`

// The net-debit sum (minor units, no sign flip) of the splits cleared against a
// reconciliation, excluding splits on soft-deleted transactions (out of the
// ledger). COALESCE 0 when nothing is cleared. This is the cleared term of
// Finalize's zero-difference gate -- byte-identical to Z9's inner SUM. The recon
// id param is CAST so sqlc types it int64 (the reconciliation_id column is
// nullable); the SUM is CAST so sqlc pins the static return type to int64.
func (q *Queries) ReconciliationClearedSum(ctx context.Context, dollar_1 int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, reconciliationClearedSum, dollar_1)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setReconciliationStatus = `-- name: SetReconciliationStatus :exec
UPDATE reconciliations SET status = ? WHERE id = ?
`

type SetReconciliationStatusParams struct {
	Status string
	ID     int64
}

// Flip a reconciliation's status (open <-> finalized, or open -> discarded). The
// store reads the current row, sets the target status, and writes it here; the
// version append reflects the new status (runs AFTER this live write).
func (q *Queries) SetReconciliationStatus(ctx context.Context, arg SetReconciliationStatusParams) error {
	_, err := q.db.ExecContext(ctx, setReconciliationStatus, arg.Status, arg.ID)
	return err
}

const setReconciliationStatement = `-- name: SetReconciliationStatement :exec
UPDATE reconciliations SET statement_date = ?, statement_balance = ? WHERE id = ?
`

type SetReconciliationStatementParams struct {
	StatementDate    string
	StatementBalance int64
	ID               int64
}

// p26.57: edit an OPEN reconciliation's statement_date + statement_balance. The
// store validates the recon is open + the inputs parse (money) before this write,
// then appends a version snapshot AFTER (so it reflects the new figures). The
// opening balance is DERIVED (prior finalized statement), not stored, so it is not
// editable here. Params: statement_date, statement_balance, id.
func (q *Queries) SetReconciliationStatement(ctx context.Context, arg SetReconciliationStatementParams) error {
	_, err := q.db.ExecContext(ctx, setReconciliationStatement, arg.StatementDate, arg.StatementBalance, arg.ID)
	return err
}

const unclearReconciliationSplits = `-- name: UnclearReconciliationSplits :exec
UPDATE splits SET reconciliation_id = NULL WHERE reconciliation_id = ?
`

// p26.58: release (un-clear) every split cleared against a reconciliation --
// reconciliation_id -> NULL for all its splits. Used on DISCARD so the abandoned
// recon's splits become available to a future reconciliation. LIVE-ONLY column
// (00014): NO split version is appended (clearing state is operational metadata, not
// audited business content). The recon is OPEN when this runs (discard guards
// status='open'), so trg_split_locked_when_finalized never fires. Param:
// reconciliation_id.
func (q *Queries) UnclearReconciliationSplits(ctx context.Context, reconciliationID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, unclearReconciliationSplits, reconciliationID)
	return err
}

const setSplitReconciliation = `-- name: SetSplitReconciliation :exec
UPDATE splits SET reconciliation_id = ? WHERE id = ?
`

type SetSplitReconciliationParams struct {
	ReconciliationID sql.NullInt64
	ID               int64
}

// Set (clear) or NULL (unclear) a split's reconciliation_id. LIVE-ONLY column
// (00014): NO split-version row is appended -- the reconciliation state of a split
// is operational metadata, not audited business content. Guarded by
// trg_split_locked_when_finalized only when a FINALIZED recon is involved; the
// store confines this to OPEN recons, so the trigger never fires on the happy path.
func (q *Queries) SetSplitReconciliation(ctx context.Context, arg SetSplitReconciliationParams) error {
	_, err := q.db.ExecContext(ctx, setSplitReconciliation, arg.ReconciliationID, arg.ID)
	return err
}

const workspaceSplits = `-- name: WorkspaceSplits :many
SELECT s.id, s.transaction_id, s.amount, s.fund_id, s.memo, s.description,
       s.reconciliation_id, t.date, t.subsidiary_id, t.memo AS txn_memo
FROM splits s
JOIN transactions t ON t.id = s.transaction_id
WHERE s.account_id = ?
  AND t.currency = ?
  AND t.deleted = 0
  AND (s.reconciliation_id IS NULL OR s.reconciliation_id = ?)
ORDER BY t.date, s.id
`

type WorkspaceSplitsParams struct {
	AccountID        int64
	Currency         string
	ReconciliationID sql.NullInt64
}

type WorkspaceSplitsRow struct {
	ID               int64
	TransactionID    int64
	Amount           int64
	FundID           sql.NullInt64
	Memo             string
	Description      string
	ReconciliationID sql.NullInt64
	Date             string
	SubsidiaryID     int64
	TxnMemo          string
}

// The p16.3 WORKSPACE split set for an OPEN reconciliation on (account, currency):
// every split on account_id whose txn is in this currency (D3) and NOT soft-deleted,
// that is either UNCLEARED (reconciliation_id IS NULL) or cleared against THIS recon
// (reconciliation_id = ?). Splits cleared in a PRIOR finalized recon are excluded --
// they are baked into the opening balance (PriorFinalizedStatementBalance), so
// showing them would double-count. Ordered ascending by (date, split id) so the
// workspace reads chronologically. Params: account_id, currency, reconciliation_id.
func (q *Queries) WorkspaceSplits(ctx context.Context, arg WorkspaceSplitsParams) ([]WorkspaceSplitsRow, error) {
	rows, err := q.db.QueryContext(ctx, workspaceSplits, arg.AccountID, arg.Currency, arg.ReconciliationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceSplitsRow
	for rows.Next() {
		var i WorkspaceSplitsRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.Amount,
			&i.FundID,
			&i.Memo,
			&i.Description,
			&i.ReconciliationID,
			&i.Date,
			&i.SubsidiaryID,
			&i.TxnMemo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
