// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report_groups.sql

package sqlc

import (
	"context"
)

const reportGrantsForUser = `-- name: ReportGrantsForUser :many
SELECT group_name
FROM user_report_grants
WHERE user_id = ?
ORDER BY group_name
`

// The report groups a user has been granted read access to (D10). Read by the
// permission-enforcement middleware ONLY when a route's Perm is ReportGroup, so
// it never taxes the anonymous / non-report hot path. ORDER BY for determinism.
func (q *Queries) ReportGrantsForUser(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, reportGrantsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var group_name string
		if err := rows.Scan(&group_name); err != nil {
			return nil, err
		}
		items = append(items, group_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReportGroup = `-- name: UpsertReportGroup :exec

INSERT INTO report_groups (name, sort)
VALUES (?, ?)
ON CONFLICT(name) DO UPDATE SET sort = excluded.sort
`

type UpsertReportGroupParams struct {
	Name string
	Sort int64
}

// report_groups is code-declared reference data (D10), synced to the db at
// startup (p06.3). It is NOT a versioned business table, so the sync is a plain
// idempotent upsert -- outside the write funnel, like currencies (rule 2 permits
// reads and reference-data upserts via sqlc). ASCII only (p04.2 sqlc quirk).
// Idempotent insert-or-update of one code-declared group, keyed by its name.
// Safe to run on every boot: an existing group has its sort refreshed, a new one
// is created. No changes/version wiring -- reference data has no audit twin.
func (q *Queries) UpsertReportGroup(ctx context.Context, arg UpsertReportGroupParams) error {
	_, err := q.db.ExecContext(ctx, upsertReportGroup, arg.Name, arg.Sort)
	return err
}
