// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report_groups.sql

package sqlc

import (
	"context"
	"database/sql"

	"cuento/internal/ids"
)

const deleteReportGrant = `-- name: DeleteReportGrant :exec
DELETE FROM user_report_grants
WHERE user_id = ? AND group_name = ?
`

type DeleteReportGrantParams struct {
	UserID    ids.UserID
	GroupName string
}

// Remove one grant. For op=delete the version row is captured BEFORE this runs
// (the live row must still exist to snapshot) -- the removal-op ordering the
// account-subsidiaries store path documents.
func (q *Queries) DeleteReportGrant(ctx context.Context, arg DeleteReportGrantParams) error {
	_, err := q.db.ExecContext(ctx, deleteReportGrant, arg.UserID, arg.GroupName)
	return err
}

const getReportGrantScope = `-- name: GetReportGrantScope :one
SELECT program_id FROM user_report_grants
WHERE user_id = ? AND group_name = ?
`

type GetReportGrantScopeParams struct {
	UserID    ids.UserID
	GroupName string
}

// The program-subtree scope of an existing (user, group) grant (p27.4): program_id
// NULL = unscoped. Returns no rows when the grant does not exist. Grant management
// reads this to decide whether a re-grant is a true no-op (same scope) or a scope
// CHANGE (revoke+grant), since the composite key is (user, group) -- the scope is a
// mutable attribute, not part of the key.
func (q *Queries) GetReportGrantScope(ctx context.Context, arg GetReportGrantScopeParams) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, getReportGrantScope, arg.UserID, arg.GroupName)
	var program_id sql.NullInt64
	err := row.Scan(&program_id)
	return program_id, err
}

const hasReportGrant = `-- name: HasReportGrant :one
SELECT COUNT(*) FROM user_report_grants
WHERE user_id = ? AND group_name = ?
`

type HasReportGrantParams struct {
	UserID    ids.UserID
	GroupName string
}

// 1 if the user already holds the grant. Grant management guards with this first
// so a re-grant is a no-op with no duplicate PK and no spurious version row --
// mirroring HasAccountSubsidiary (the composite-membership pattern).
func (q *Queries) HasReportGrant(ctx context.Context, arg HasReportGrantParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasReportGrant, arg.UserID, arg.GroupName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertReportGrant = `-- name: InsertReportGrant :exec
INSERT INTO user_report_grants (user_id, group_name, program_id)
VALUES (?, ?, ?)
`

type InsertReportGrantParams struct {
	UserID    ids.UserID
	GroupName string
	ProgramID sql.NullInt64
}

// Add one (user_id, group_name) grant with an optional program-subtree scope
// (program_id NULL = unscoped). Callers guard with HasReportGrant first (membership
// is a set keyed on user+group; the PK forbids duplicates -- a scope CHANGE is a
// revoke+grant, not an update). The version append that follows (op='create')
// snapshots this row (incl. program_id) under the acting admin's change.
func (q *Queries) InsertReportGrant(ctx context.Context, arg InsertReportGrantParams) error {
	_, err := q.db.ExecContext(ctx, insertReportGrant, arg.UserID, arg.GroupName, arg.ProgramID)
	return err
}

const insertReportGrantVersion = `-- name: InsertReportGrantVersion :exec
INSERT INTO user_report_grants_versions
  (entity_id, change_id, valid_from, op, group_name, program_id)
SELECT g.user_id, c.id, c.at, ?, g.group_name, g.program_id
FROM user_report_grants g, changes c
WHERE c.id = ? AND g.user_id = ? AND g.group_name = ?
`

type InsertReportGrantVersionParams struct {
	Op        string
	ID        ids.ChangeID
	UserID    ids.UserID
	GroupName string
}

// Snapshot-from-live version append for a COMPOSITE (user_id, group_name) grant
// (00006 twin: entity_id = user_id, snapshot group_name). For op='create' this
// runs AFTER the live insert; for op='delete' BEFORE the live delete (the row
// must still exist to snapshot). Params (positional): op, change_id, user_id,
// group_name -> generated fields Op, ID, UserID, GroupName. Mirrors
// InsertAccountSubsidiaryVersion. ASCII only (p04.2 sqlc quirk).
func (q *Queries) InsertReportGrantVersion(ctx context.Context, arg InsertReportGrantVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertReportGrantVersion,
		arg.Op,
		arg.ID,
		arg.UserID,
		arg.GroupName,
	)
	return err
}

const listReportGroups = `-- name: ListReportGroups :many
SELECT name, sort FROM report_groups ORDER BY sort, name
`

// All code-declared report groups, in their declared sort order (p13.2): the set
// of grant checkboxes the admin per-user page offers. A read (reference data).
func (q *Queries) ListReportGroups(ctx context.Context) ([]ReportGroup, error) {
	rows, err := q.db.QueryContext(ctx, listReportGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportGroup
	for rows.Next() {
		var i ReportGroup
		if err := rows.Scan(&i.Name, &i.Sort); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportGrantsForUser = `-- name: ReportGrantsForUser :many
SELECT group_name, program_id
FROM user_report_grants
WHERE user_id = ?
ORDER BY group_name
`

type ReportGrantsForUserRow struct {
	GroupName string
	ProgramID sql.NullInt64
}

// The report groups a user has been granted read access to, WITH each grant's
// optional program-subtree scope (D10, p27.4). program_id NULL = unscoped
// (org-wide). Read by the permission-enforcement middleware ONLY when a route's
// Perm is ReportGroup, so it never taxes the anonymous / non-report hot path.
// ORDER BY for determinism.
func (q *Queries) ReportGrantsForUser(ctx context.Context, userID ids.UserID) ([]ReportGrantsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, reportGrantsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportGrantsForUserRow
	for rows.Next() {
		var i ReportGrantsForUserRow
		if err := rows.Scan(&i.GroupName, &i.ProgramID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReportGroup = `-- name: UpsertReportGroup :exec

INSERT INTO report_groups (name, sort)
VALUES (?, ?)
ON CONFLICT(name) DO UPDATE SET sort = excluded.sort
`

type UpsertReportGroupParams struct {
	Name string
	Sort int64
}

// report_groups is code-declared reference data (D10), synced to the db at
// startup (p06.3). It is NOT a versioned business table, so the sync is a plain
// idempotent upsert -- outside the write funnel, like currencies (rule 2 permits
// reads and reference-data upserts via sqlc). ASCII only (p04.2 sqlc quirk).
// Idempotent insert-or-update of one code-declared group, keyed by its name.
// Safe to run on every boot: an existing group has its sort refreshed, a new one
// is created. No changes/version wiring -- reference data has no audit twin.
func (q *Queries) UpsertReportGroup(ctx context.Context, arg UpsertReportGroupParams) error {
	_, err := q.db.ExecContext(ctx, upsertReportGroup, arg.Name, arg.Sort)
	return err
}
