// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: smoke.sql

package sqlc

import (
	"context"
)

const selectOne = `-- name: SelectOne :one
SELECT 1 AS one
`

// Schema-less round-trip: the migration baseline declares no tables yet
// (p01.3). SELECT 1 exercises the generated query layer without depending on
// business schema; real queries land alongside their tables in later phases.
func (q *Queries) SelectOne(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, selectOne)
	var one int64
	err := row.Scan(&one)
	return one, err
}
