// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const accountIsLeaf = `-- name: AccountIsLeaf :one

SELECT NOT EXISTS (SELECT 1 FROM accounts c WHERE c.parent_id = ?) AS is_leaf
`

// ---------------------------------------------------------------------------
// validation reads (inside the funnel's fn, on the tx-bound queries)
// ---------------------------------------------------------------------------
// 1 when the account has NO children (a leaf; D11). A placeholder (>=1 child)
// holds no splits. Used to raise ErrPlaceholderAccount before the trigger fires.
func (q *Queries) AccountIsLeaf(ctx context.Context, parentID sql.NullInt64) (bool, error) {
	row := q.db.QueryRowContext(ctx, accountIsLeaf, parentID)
	var is_leaf bool
	err := row.Scan(&is_leaf)
	return is_leaf, err
}

const deleteSplit = `-- name: DeleteSplit :exec
DELETE FROM splits WHERE id = ?
`

// Hard-delete one split row (the replace-set diff removes splits dropped from the
// input). For op='delete' the version row is captured BEFORE this runs (the live
// row must still exist to snapshot from) -- the removal-op ordering.
func (q *Queries) DeleteSplit(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSplit, id)
	return err
}

const getPayee = `-- name: GetPayee :one
SELECT id, name, active FROM payees WHERE id = ?
`

func (q *Queries) GetPayee(ctx context.Context, id int64) (Payee, error) {
	row := q.db.QueryRowContext(ctx, getPayee, id)
	var i Payee
	err := row.Scan(&i.ID, &i.Name, &i.Active)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, date, subsidiary_id, payee_id, memo, currency, deleted
FROM transactions
WHERE id = ?
`

func (q *Queries) GetTransaction(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.SubsidiaryID,
		&i.PayeeID,
		&i.Memo,
		&i.Currency,
		&i.Deleted,
	)
	return i, err
}

const hasAccountSubsidiaryMap = `-- name: HasAccountSubsidiaryMap :one
SELECT EXISTS (
  SELECT 1 FROM account_subsidiaries WHERE account_id = ? AND subsidiary_id = ?
) AS mapped
`

type HasAccountSubsidiaryMapParams struct {
	AccountID    int64
	SubsidiaryID int64
}

// 1 when account A is mapped to subsidiary S (D18). Used to raise
// ErrAccountNotInSubsidiary: every split account must include the txn's subsidiary.
func (q *Queries) HasAccountSubsidiaryMap(ctx context.Context, arg HasAccountSubsidiaryMapParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasAccountSubsidiaryMap, arg.AccountID, arg.SubsidiaryID)
	var mapped bool
	err := row.Scan(&mapped)
	return mapped, err
}

const hasFundSubsidiaryMap = `-- name: HasFundSubsidiaryMap :one
SELECT EXISTS (
  SELECT 1 FROM fund_subsidiaries WHERE fund_id = ? AND subsidiary_id = ?
) AS scoped
`

type HasFundSubsidiaryMapParams struct {
	FundID       int64
	SubsidiaryID int64
}

// 1 when fund F is scoped to subsidiary S (D20/Z13). Used to raise
// ErrFundSubsidiaryScope: a txn's subsidiary must be in its split fund's set.
func (q *Queries) HasFundSubsidiaryMap(ctx context.Context, arg HasFundSubsidiaryMapParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasFundSubsidiaryMap, arg.FundID, arg.SubsidiaryID)
	var scoped bool
	err := row.Scan(&scoped)
	return scoped, err
}

const insertPayee = `-- name: InsertPayee :one


INSERT INTO payees (name, active)
VALUES (?, 1)
RETURNING id
`

// p08.2: transaction/split/payee operations (D2, D18, D20, D21, D24). All SQL for
// the store's transaction methods lives here (rule 6). This copies the
// version-append convention established in subsidiaries.sql (p04.2) and the
// snapshot-from-live pattern: the entity op does the live write inside the
// funnel's fn, then appends a snapshot-from-live version row, so each version row
// is byte-identical to its live row (Z3 can never diverge) and valid_from ==
// changes.at BY CONSTRUCTION.
//
// transactions/splits use SOFT-DELETE only for the header (rule 14): DeleteTransaction
// flips transactions.deleted and appends a transactions_versions op='delete'; the
// splits are left in place (the as-of query excludes the txn by its own delete row).
// An UpdateTransaction split REMOVAL is a hard live DELETE of that split row plus a
// splits_versions op='delete' (captured BEFORE the live delete, snapshot-from-live).
//
// Query names are DISTINCT across the whole sqlc package.
//
// NOTE: keep every comment and identifier in this file PURE ASCII. sqlc v1.31.1
// miscounts byte offsets when a query file contains multi-byte UTF-8, corrupting
// the generated SQL for the WHOLE file (see docs/DECISIONS.md p04.2).
// ---------------------------------------------------------------------------
// payees (minimal; autocomplete is p12.3)
// ---------------------------------------------------------------------------
// Live insert of a payee. name is UNIQUE COLLATE NOCASE (schema). Returns the id.
func (q *Queries) InsertPayee(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPayee, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPayeeVersion = `-- name: InsertPayeeVersion :exec
INSERT INTO payees_versions
  (entity_id, change_id, valid_from, op, name, active)
SELECT p.id, c.id, c.at, ?, p.name, p.active
FROM payees p, changes c
WHERE c.id = ? AND p.id = ?
`

type InsertPayeeVersionParams struct {
	Op   string
	ID   int64
	ID_2 int64
}

// Snapshot-from-live version append for payees (STANDARD single-id entity,
// entity_id = payees.id). Runs AFTER the live insert. Snapshot column set matches
// 00010_transactions_splits.sql exactly (name, active). Params (positional, each
// used once): op, change_id, entity_id -> generated Op, ID (change_id), ID_2.
func (q *Queries) InsertPayeeVersion(ctx context.Context, arg InsertPayeeVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertPayeeVersion, arg.Op, arg.ID, arg.ID_2)
	return err
}

const insertSplit = `-- name: InsertSplit :one

INSERT INTO splits
  (transaction_id, account_id, amount, fund_id, program_id, functional_class, memo, position)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertSplitParams struct {
	TransactionID   int64
	AccountID       int64
	Amount          int64
	FundID          sql.NullInt64
	ProgramID       sql.NullInt64
	FunctionalClass sql.NullString
	Memo            string
	Position        int64
}

// ---------------------------------------------------------------------------
// splits
// ---------------------------------------------------------------------------
// Live insert of one split line. amount is int64 minor units, net-debit sign
// (D1/D2), CHECK amount <> 0. fund_id NULL == unrestricted (D20). program_id
// required iff R/E account (trigger backstop); functional_class required iff
// expense account (trigger backstop); the store DEFAULTS both before insert so the
// triggers never fire on the happy path. Returns the new id.
func (q *Queries) InsertSplit(ctx context.Context, arg InsertSplitParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertSplit,
		arg.TransactionID,
		arg.AccountID,
		arg.Amount,
		arg.FundID,
		arg.ProgramID,
		arg.FunctionalClass,
		arg.Memo,
		arg.Position,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSplitVersion = `-- name: InsertSplitVersion :exec
INSERT INTO splits_versions
  (entity_id, change_id, valid_from, op, transaction_id, account_id, amount,
   fund_id, program_id, functional_class, memo, position)
SELECT s.id, c.id, c.at, ?, s.transaction_id, s.account_id, s.amount,
       s.fund_id, s.program_id, s.functional_class, s.memo, s.position
FROM splits s, changes c
WHERE c.id = ? AND s.id = ?
`

type InsertSplitVersionParams struct {
	Op   string
	ID   int64
	ID_2 int64
}

// Snapshot-from-live version append for splits (STANDARD single-id entity,
// entity_id = splits.id). For op='create'/'update' this runs AFTER the live write;
// for op='delete' it runs BEFORE the live DELETE (the row must still exist to
// snapshot). Snapshot column set matches 00010 exactly. Params (positional): op,
// change_id, entity_id -> generated Op, ID (change_id), ID_2.
func (q *Queries) InsertSplitVersion(ctx context.Context, arg InsertSplitVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertSplitVersion, arg.Op, arg.ID, arg.ID_2)
	return err
}

const insertTransaction = `-- name: InsertTransaction :one

INSERT INTO transactions (date, subsidiary_id, payee_id, memo, currency, deleted)
VALUES (?, ?, ?, ?, ?, 0)
RETURNING id
`

type InsertTransactionParams struct {
	Date         string
	SubsidiaryID int64
	PayeeID      sql.NullInt64
	Memo         string
	Currency     string
}

// ---------------------------------------------------------------------------
// transactions
// ---------------------------------------------------------------------------
// Live insert of the transaction header (D18: exactly one subsidiary; D3: single
// currency). deleted defaults to 0. Returns the new id.
func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertTransaction,
		arg.Date,
		arg.SubsidiaryID,
		arg.PayeeID,
		arg.Memo,
		arg.Currency,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTransactionVersion = `-- name: InsertTransactionVersion :exec
INSERT INTO transactions_versions
  (entity_id, change_id, valid_from, op, date, subsidiary_id, payee_id, memo, currency, deleted)
SELECT t.id, c.id, c.at, ?, t.date, t.subsidiary_id, t.payee_id, t.memo, t.currency, t.deleted
FROM transactions t, changes c
WHERE c.id = ? AND t.id = ?
`

type InsertTransactionVersionParams struct {
	Op   string
	ID   int64
	ID_2 int64
}

// Snapshot-from-live version append for transactions (STANDARD single-id entity).
// Runs AFTER the live write. Snapshot column set matches 00010 exactly. Params
// (positional): op, change_id, entity_id -> generated Op, ID (change_id), ID_2.
func (q *Queries) InsertTransactionVersion(ctx context.Context, arg InsertTransactionVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertTransactionVersion, arg.Op, arg.ID, arg.ID_2)
	return err
}

const programSubtreeIDs = `-- name: ProgramSubtreeIDs :many
WITH RECURSIVE subtree(id, parent_id, name, active, sort_order) AS (
  SELECT p0.id, p0.parent_id, p0.name, p0.active, p0.sort_order
  FROM programs p0 WHERE p0.id = ?
  UNION ALL
  SELECT p.id, p.parent_id, p.name, p.active, p.sort_order
  FROM programs p JOIN subtree ON p.parent_id = subtree.id
)
SELECT subtree.id FROM subtree
`

// The program ids in the subtree rooted at R (self included). Used for the
// fund-program scope check (D20): an R/E split tagged a fund whose program scope R
// is set must carry a program inside R's subtree, else ErrFundProgramScope. Like
// ProgramDescendants, the store builds a set and checks membership in Go (sqlc's
// sqlite analyzer rejects a recursive-CTE alias in an outer EXISTS/WHERE).
func (q *Queries) ProgramSubtreeIDs(ctx context.Context, id int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, programSubtreeIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rootProgram = `-- name: RootProgram :one
SELECT id, parent_id, name, active, sort_order
FROM programs
WHERE parent_id IS NULL
`

// The single root program (parent_id IS NULL; the seeded "General", D24). The
// program-defaulting fallback for an R/E split with no account default. Looked up
// rather than hardcoded id 1.
func (q *Queries) RootProgram(ctx context.Context) (Program, error) {
	row := q.db.QueryRowContext(ctx, rootProgram)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Active,
		&i.SortOrder,
	)
	return i, err
}

const softDeleteTransaction = `-- name: SoftDeleteTransaction :exec
UPDATE transactions SET deleted = 1 WHERE id = ?
`

// Soft-delete (rule 14): flip the deleted flag. The row is never removed. The
// store appends a transactions_versions op='delete' after this.
func (q *Queries) SoftDeleteTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteTransaction, id)
	return err
}

const splitUsesAccountInSubsidiary = `-- name: SplitUsesAccountInSubsidiary :one

SELECT EXISTS (
  SELECT 1 FROM splits s
  JOIN transactions t ON t.id = s.transaction_id
  WHERE s.account_id = ? AND t.subsidiary_id = ? AND t.deleted = 0
) AS in_use
`

type SplitUsesAccountInSubsidiaryParams struct {
	AccountID    int64
	SubsidiaryID int64
}

// ---------------------------------------------------------------------------
// deferred p08 guards (complete the p05.2 / p07.3 TODOs)
// ---------------------------------------------------------------------------
// 1 when a split on account A belongs to a NON-DELETED transaction whose
// subsidiary is S. Completes the p05.2 guard: removing subsidiary S from account A
// is blocked while such a split exists (ErrSubInUseByChild extended to splits).
func (q *Queries) SplitUsesAccountInSubsidiary(ctx context.Context, arg SplitUsesAccountInSubsidiaryParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, splitUsesAccountInSubsidiary, arg.AccountID, arg.SubsidiaryID)
	var in_use bool
	err := row.Scan(&in_use)
	return in_use, err
}

const splitUsesFundInSubsidiary = `-- name: SplitUsesFundInSubsidiary :one
SELECT EXISTS (
  SELECT 1 FROM splits s
  JOIN transactions t ON t.id = s.transaction_id
  WHERE s.fund_id = ? AND t.subsidiary_id = ? AND t.deleted = 0
) AS in_use
`

type SplitUsesFundInSubsidiaryParams struct {
	FundID       sql.NullInt64
	SubsidiaryID int64
}

// 1 when a split with fund_id F belongs to a NON-DELETED transaction whose
// subsidiary is S. Completes the p07.3 guard: removing subsidiary S from fund F is
// blocked while such a split exists (ErrFundSubInUseBySplit).
func (q *Queries) SplitUsesFundInSubsidiary(ctx context.Context, arg SplitUsesFundInSubsidiaryParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, splitUsesFundInSubsidiary, arg.FundID, arg.SubsidiaryID)
	var in_use bool
	err := row.Scan(&in_use)
	return in_use, err
}

const splitVersionsAsOf = `-- name: SplitVersionsAsOf :many
SELECT entity_id, op, transaction_id, account_id, amount, fund_id, program_id,
       functional_class, memo, position
FROM splits_versions
WHERE transaction_id = ? AND valid_from <= ?
ORDER BY entity_id, valid_from DESC, id DESC
`

type SplitVersionsAsOfParams struct {
	TransactionID int64
	ValidFrom     string
}

type SplitVersionsAsOfRow struct {
	EntityID        int64
	Op              string
	TransactionID   int64
	AccountID       int64
	Amount          int64
	FundID          sql.NullInt64
	ProgramID       sql.NullInt64
	FunctionalClass sql.NullString
	Memo            string
	Position        int64
}

// Every split version row for a transaction with valid_from <= at, ordered so the
// store can take the FIRST row per entity_id (the latest snapshot for that split)
// and drop op='delete'. transaction_id filters to this txn's splits. Tiebreak
// matches AssertVersioned.
func (q *Queries) SplitVersionsAsOf(ctx context.Context, arg SplitVersionsAsOfParams) ([]SplitVersionsAsOfRow, error) {
	rows, err := q.db.QueryContext(ctx, splitVersionsAsOf, arg.TransactionID, arg.ValidFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SplitVersionsAsOfRow
	for rows.Next() {
		var i SplitVersionsAsOfRow
		if err := rows.Scan(
			&i.EntityID,
			&i.Op,
			&i.TransactionID,
			&i.AccountID,
			&i.Amount,
			&i.FundID,
			&i.ProgramID,
			&i.FunctionalClass,
			&i.Memo,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const splitsByTransaction = `-- name: SplitsByTransaction :many
SELECT id, transaction_id, account_id, amount, fund_id, program_id,
       functional_class, memo, position
FROM splits
WHERE transaction_id = ?
ORDER BY position, id
`

// The current live split set for one transaction, in display order.
func (q *Queries) SplitsByTransaction(ctx context.Context, transactionID int64) ([]Split, error) {
	rows, err := q.db.QueryContext(ctx, splitsByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Split
	for rows.Next() {
		var i Split
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AccountID,
			&i.Amount,
			&i.FundID,
			&i.ProgramID,
			&i.FunctionalClass,
			&i.Memo,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transactionVersionAsOf = `-- name: TransactionVersionAsOf :one

SELECT op, date, subsidiary_id, payee_id, memo, currency, deleted
FROM transactions_versions
WHERE entity_id = ? AND valid_from <= ?
ORDER BY valid_from DESC, id DESC
LIMIT 1
`

type TransactionVersionAsOfParams struct {
	EntityID  int64
	ValidFrom string
}

type TransactionVersionAsOfRow struct {
	Op           string
	Date         string
	SubsidiaryID int64
	PayeeID      sql.NullInt64
	Memo         string
	Currency     string
	Deleted      int64
}

// ---------------------------------------------------------------------------
// as-of reconstruction (D4/D5) -- resolved in Go (like Effective990Codes) to keep
// each param single-use and avoid the sqlc numbered-param quirk on `at` reuse.
// ---------------------------------------------------------------------------
// The transaction header as of a time: the latest transactions_versions row with
// valid_from <= at (op='delete' means the txn is absent -- the store excludes it).
// Tiebreak (valid_from DESC, id DESC) matches AssertVersioned's append order.
func (q *Queries) TransactionVersionAsOf(ctx context.Context, arg TransactionVersionAsOfParams) (TransactionVersionAsOfRow, error) {
	row := q.db.QueryRowContext(ctx, transactionVersionAsOf, arg.EntityID, arg.ValidFrom)
	var i TransactionVersionAsOfRow
	err := row.Scan(
		&i.Op,
		&i.Date,
		&i.SubsidiaryID,
		&i.PayeeID,
		&i.Memo,
		&i.Currency,
		&i.Deleted,
	)
	return i, err
}

const updateSplit = `-- name: UpdateSplit :exec
UPDATE splits
SET account_id = ?, amount = ?, fund_id = ?, program_id = ?,
    functional_class = ?, memo = ?, position = ?
WHERE id = ?
`

type UpdateSplitParams struct {
	AccountID       int64
	Amount          int64
	FundID          sql.NullInt64
	ProgramID       sql.NullInt64
	FunctionalClass sql.NullString
	Memo            string
	Position        int64
	ID              int64
}

// Live update of one split's business columns (replace-set diff: only splits that
// actually changed reach this). id last.
func (q *Queries) UpdateSplit(ctx context.Context, arg UpdateSplitParams) error {
	_, err := q.db.ExecContext(ctx, updateSplit,
		arg.AccountID,
		arg.Amount,
		arg.FundID,
		arg.ProgramID,
		arg.FunctionalClass,
		arg.Memo,
		arg.Position,
		arg.ID,
	)
	return err
}

const updateTransaction = `-- name: UpdateTransaction :exec
UPDATE transactions
SET date = ?, subsidiary_id = ?, payee_id = ?, memo = ?, currency = ?, deleted = ?
WHERE id = ?
`

type UpdateTransactionParams struct {
	Date         string
	SubsidiaryID int64
	PayeeID      sql.NullInt64
	Memo         string
	Currency     string
	Deleted      int64
	ID           int64
}

// Live update of the header fields (date/payee/memo; subsidiary and currency may
// also change on an edit). deleted is carried through by the store (never flipped
// here -- soft-delete is its own query).
func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) error {
	_, err := q.db.ExecContext(ctx, updateTransaction,
		arg.Date,
		arg.SubsidiaryID,
		arg.PayeeID,
		arg.Memo,
		arg.Currency,
		arg.Deleted,
		arg.ID,
	)
	return err
}
