// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countHumanUsers = `-- name: CountHumanUsers :one
SELECT COUNT(*) FROM users WHERE id <> 1
`

// Bootstrap hint (p06.4): count real operators, excluding the seeded system
// user (id 1). Zero means the operator still needs to create the first account,
// so serve logs the `cuento user add ... --admin` hint on start.
func (q *Queries) CountHumanUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countHumanUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUser = `-- name: GetUser :one

SELECT id, username, display_name, created_at, disabled_at
FROM users
WHERE id = ?
`

type GetUserRow struct {
	ID          int64
	Username    string
	DisplayName string
	CreatedAt   string
	DisabledAt  sql.NullString
}

// p06.1 adds InsertUser + InsertUserVersion. Keep this file PURE ASCII: sqlc
// v1.31.1 miscounts byte offsets on multi-byte UTF-8 and corrupts the WHOLE
// file's generated SQL (see docs/DECISIONS.md p04.2).
func (q *Queries) GetUser(ctx context.Context, id int64) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (username, display_name, created_at, password_hash, is_admin, txn_perm)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertUserParams struct {
	Username     string
	DisplayName  string
	CreatedAt    string
	PasswordHash sql.NullString
	IsAdmin      int64
	TxnPerm      string
}

// Live insert of a user. password_hash is nullable (a passwordless user, like
// the system user, passes NULL). Settings columns are omitted so their schema
// DEFAULTs apply; the version append reads them back from the live row. Returns
// the new id for the store to snapshot + return.
func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertUser,
		arg.Username,
		arg.DisplayName,
		arg.CreatedAt,
		arg.PasswordHash,
		arg.IsAdmin,
		arg.TxnPerm,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertUserVersion = `-- name: InsertUserVersion :exec
INSERT INTO users_versions
  (entity_id, change_id, valid_from, op,
   username, display_name, created_at, disabled_at, is_admin, txn_perm,
   locale, date_format, number_format, display_mode, neg_style, theme,
   default_subsidiary_id)
SELECT u.id, c.id, c.at, ?,
       u.username, u.display_name, u.created_at, u.disabled_at, u.is_admin, u.txn_perm,
       u.locale, u.date_format, u.number_format, u.display_mode, u.neg_style, u.theme,
       u.default_subsidiary_id
FROM users u, changes c
WHERE c.id = ? AND u.id = ?
`

type InsertUserVersionParams struct {
	Op   string
	ID   int64
	ID_2 int64
}

// Snapshot-from-live version append for users (rule 5, D4). Runs AFTER the live
// insert; copies every business column EXCEPT password_hash, which is
// DELIBERATELY omitted so the audit trail never carries the secret (rule 5).
// valid_from is the change's own `at`, so valid_from == changes.at BY
// CONSTRUCTION. Snapshot column set matches 00006_credentials_perms.sql exactly.
//
// Params are PLAIN POSITIONAL (?), each used once (op, change_id, entity_id), so
// no numbered/named form is needed -- matching InsertSubsidiaryVersion's shape.
// Generated struct fields: Op, ID (change_id = c.id), ID_2 (entity_id = u.id).
// The store wraps that behind one insertUserVersion helper.
func (q *Queries) InsertUserVersion(ctx context.Context, arg InsertUserVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertUserVersion, arg.Op, arg.ID, arg.ID_2)
	return err
}

const setUserDisabled = `-- name: SetUserDisabled :exec
UPDATE users SET disabled_at = ? WHERE id = ?
`

type SetUserDisabledParams struct {
	DisabledAt sql.NullString
	ID         int64
}

// Live update of a user's disabled_at (p06.4 `user disable`). A disabled user
// cannot log in (login enforces this). Versioned as op='update'; disabled_at IS
// part of the users_versions snapshot, so the audit trail records the disabling.
func (q *Queries) SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) error {
	_, err := q.db.ExecContext(ctx, setUserDisabled, arg.DisabledAt, arg.ID)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = ? WHERE id = ?
`

type SetUserPasswordParams struct {
	PasswordHash sql.NullString
	ID           int64
}

// Live update of a user's password_hash (p06.4 `user passwd`). The version append
// (InsertUserVersion) that follows DELIBERATELY omits password_hash (rule 5), so
// the new secret enters only the live table, never the audit trail.
func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, setUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const setUserTheme = `-- name: SetUserTheme :exec
UPDATE users SET theme = ? WHERE id = ?
`

type SetUserThemeParams struct {
	Theme string
	ID    int64
}

// Live update of a user's theme preference (p10.2 POST /theme). Versioned as
// op='update'; theme IS part of the users_versions snapshot, so the audit trail
// records the change. The handler also persists a cookie for the no-flash SSR
// read; this write makes the preference durable across devices for a logged-in
// user.
func (q *Queries) SetUserTheme(ctx context.Context, arg SetUserThemeParams) error {
	_, err := q.db.ExecContext(ctx, setUserTheme, arg.Theme, arg.ID)
	return err
}

const updateUserSettings = `-- name: UpdateUserSettings :exec
UPDATE users
SET locale = ?, date_format = ?, number_format = ?, display_mode = ?,
    neg_style = ?, theme = ?, default_subsidiary_id = ?
WHERE id = ?
`

type UpdateUserSettingsParams struct {
	Locale              string
	DateFormat          string
	NumberFormat        string
	DisplayMode         string
	NegStyle            string
	Theme               string
	DefaultSubsidiaryID sql.NullInt64
	ID                  int64
}

// Live update of a user's personal settings (p13.1 /settings): the UI locale, the
// money/date display columns, the theme, and the (nullable) default subsidiary. The
// version append (InsertUserVersion) that follows snapshots ALL of these from the
// live row under the SAME change, so the audit trail records who changed which
// preferences. password_hash is untouched (and never in the snapshot, rule 5).
// Plain positional ? params (each used once); ASCII-only file (sqlc byte-offset
// gotcha, DECISIONS p04.2).
func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateUserSettings,
		arg.Locale,
		arg.DateFormat,
		arg.NumberFormat,
		arg.DisplayMode,
		arg.NegStyle,
		arg.Theme,
		arg.DefaultSubsidiaryID,
		arg.ID,
	)
	return err
}

const userByID = `-- name: UserByID :one
SELECT id, username, disabled_at, txn_perm, is_admin, locale, theme,
       date_format, number_format, display_mode, neg_style,
       default_subsidiary_id
FROM users
WHERE id = ?
`

type UserByIDRow struct {
	ID                  int64
	Username            string
	DisabledAt          sql.NullString
	TxnPerm             string
	IsAdmin             int64
	Locale              string
	Theme               string
	DateFormat          string
	NumberFormat        string
	DisplayMode         string
	NegStyle            string
	DefaultSubsidiaryID sql.NullInt64
}

// Session-resolution lookup (p06.2): the middleware turns a stored user id back
// into the current identity + its UI language and money-display settings on every
// authenticated request. Kept separate from GetUser (whose projection is pinned by
// sqlc/users_changes_test.go, p06.1) so this step touches no existing query.
// p11.1 extends the projection with the four money/date format columns so every
// render path can honor per-user settings (rule 10) without a second query; their
// DB defaults (US/signed/minus/ISO) apply for a session that never changed them.
// p12.2 adds default_subsidiary_id (nullable): the transaction editor defaults its
// header subsidiary to the user's setting, else the sole/root sub -- resolved here
// so the editor needs no second query.
func (q *Queries) UserByID(ctx context.Context, id int64) (UserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, userByID, id)
	var i UserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisabledAt,
		&i.TxnPerm,
		&i.IsAdmin,
		&i.Locale,
		&i.Theme,
		&i.DateFormat,
		&i.NumberFormat,
		&i.DisplayMode,
		&i.NegStyle,
		&i.DefaultSubsidiaryID,
	)
	return i, err
}

const userByUsername = `-- name: UserByUsername :one
SELECT id, password_hash, disabled_at, locale
FROM users
WHERE username = ?
`

type UserByUsernameRow struct {
	ID           int64
	PasswordHash sql.NullString
	DisabledAt   sql.NullString
	Locale       string
}

// Login lookup (p06.2). Returns the credential + the columns the auth/lang
// middleware needs: password_hash (nullable; the system user has none),
// disabled_at (a disabled user cannot log in), and locale (drives the
// post-login UI language). A NULL row (no such username) is a sql.ErrNoRows the
// caller maps to the SAME uniform error as a wrong password (no user
// enumeration, rule 13).
func (q *Queries) UserByUsername(ctx context.Context, username string) (UserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, userByUsername, username)
	var i UserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.DisabledAt,
		&i.Locale,
	)
	return i, err
}

const userIDByUsername = `-- name: UserIDByUsername :one
SELECT id FROM users WHERE username = ?
`

// CLI lookup (p06.4): passwd/disable take a username; resolve it to the id the
// versioned store methods need. A missing username is sql.ErrNoRows the CLI maps
// to a clean "no such user" error.
func (q *Queries) UserIDByUsername(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, userIDByUsername, username)
	var id int64
	err := row.Scan(&id)
	return id, err
}
